### ISSUE TITLE
Detects semicolon as an invalid character.

### ISSUE THREAD

**Issue by githuboftigran** [Leonidas-from-XIV/node-xml2js#100]
It says:

[Error: Invalid character entity
Line: 8
Column: 26
Char: ;]

why? And what characters are invalid too?

**Comment by kate008** [comment]
[Error: Invalid character in entity name
Line: 464
Column: 27
Char: ]
Showing this error in xml2js.This error is shown only for some xml files.Please help me how to resolve this.
I am not able to find what is happening

**Comment by Izhaki** [comment]
Same problem here. Trying to parse [this XML file](https://github.com/opencypher/openCypher/blob/master/grammar/start.xml) and get:

```
Error: Invalid character entity
Line: 30
Column: 14
Char: ;
```
