### ISSUE TITLE
While parsing, numeric values in source XML are created as Strings in JSON

### ISSUE THREAD

**Issue by kford** [Leonidas-from-XIV/node-xml2js#108]
The below snippet of code from a node.js API is parsing  <YEAR>1985</YEAR>  into  "YEAR": "1985" instead of "YEAR": 1985.  Is this the expected behavior?

      parser = new xml2js.Parser({"explicitArray":false});
      parser.parseString(xmlString, function(err, result) {
        if (err) {
          // ...
        }

        res.send(result);
      });

**Comment by rochal** [comment]
Actually, it would be great to add function to allow us to parse the values ourselves.. similar concept as `tagNameProcessors` but for values, we could call it `valueProcessor`. In a way, you're already "treating" all values with a processor called `trim`, but having that as a function available to us would be great.

And yes, valid point, in XML everything is string, but considering most of the times we know what XML we're dealing with we should be able to write a code and make that call.

For instance, I'd love to use this `valueProcessor` in my code, to automatically cast integers and floats:
```
function castIntFloat(value) {
  if (!isNaN(value)) {
    value = (value%1===0) ? parseInt(value, 10) : value(primitive);
  }
  return value;
}
```

**Comment by Leonidas-from-XIV** [comment]
That is a valid point, I'd be open to a PR with this feature. And maybe some bult-in preprocessors, shipped with the library.
