### ISSUE TITLE
Builder doesn't support partial file generation

### ISSUE THREAD

**Issue by LorenzGardner** [Leonidas-from-XIV/node-xml2js#109]
I want to use the xml2js bidirectional support (awesome addition btw), to generate a sections of an xml document and string it together with other sections.

This comes in handy for instance if you want to stream stuff to a file in chunks rather than all in one go, or if you want to generate a section by hand.

The issue is every call to buildObject starts the block off with 
<?xml version="1.0" encoding="UTF-8" standalone="yes">

An option to suppress that would be ideal.

**Comment by LorenzGardner** [comment]
Poke: Looks like the headless option is supported down stream now.
Of course the workaround of removing the unwanted bit from the return string is still working just fine.

**Comment by Leonidas-from-XIV** [comment]
Yeah, I think we can add this now. Do you want to submit a PR or should I look into it?

**Comment by jcsahnwaldt** [comment]
I think this can be closed, right? If I understand correctly, `headless` solved this issue.

**Comment by Leonidas-from-XIV** [comment]
True.
