### ISSUE TITLE
renderOpts being ignored

### ISSUE THREAD

**Issue by gazzer82** [Leonidas-from-XIV/node-xml2js#111]
I am converting some XML to JSON, which is working as expected, but when sending it back to XML it's adding a lot of newline and whitespace that is causing havoc with my parser.

I have tried the following but it doesn't seem to make any difference:

```
        var parseString = require('xml2js').parseString
        parseString(data, function (err, result) {
        //console.dir(result)
        response = JSON.stringify(result);
        //console.log(response);
        responseJSON = JSON.parse(response);
        //console.log(responseJSON);

        var builder = new xml2js.Builder({ 'pretty': false});
        responseXML = builder.buildObject(responseJSON);
```

I assume i am missing something obvious??

Thanks

Gareth

**Comment by rparanjpe-tesla** [comment]
This is an old issue, but it looks like you're not passing in the renderOpts object correctly. You should be instantiating the Builder object as:

```var builder = new xml2js.Builder({renderOpts: {pretty: false}});```

Maybe that can be clarified in the README @Leonidas-from-XIV ?

**Comment by Leonidas-from-XIV** [comment]
@rparanjpe-tesla Yes, I'm always for improving the README! Want to send a PR?

**Comment by knoxcard** [comment]
@gazzer82 - close issue?

**Comment by gazzer82** [comment]
Yes this sorted it, idiot factor!
