### ISSUE TITLE
is  it possible to write xml header with xml builder ?

### ISSUE THREAD

**Issue by mderazon** [Leonidas-from-XIV/node-xml2js#117]
`<?xml …>` is supported somehow ?

**Comment by raskri** [comment]
How can I remove the standalone="yes" attribute?
var builder = new xml2js.Builder({
            xmldec: {
              'version': '1.0',
              'encoding': 'UTF-8',
              'standalone': false <---- remove
            }
          });

**Comment by raskri** [comment]
Setting: 'standalone': null fixed solved it.

**Comment by alexrosenfeld10** [comment]
Is it possible to write without the `<?xml>` header at all? Just the raw tags, no header whatsoever

**Comment by alexrosenfeld10** [comment]
Never mind, found this: https://github.com/Leonidas-from-XIV/node-xml2js/pull/136

**Comment by MoySantanaV** [comment]
> Is it possible to write without the `<?xml>` header at all? Just the raw tags, no header whatsoever

use xml2js.Builder({headless: true})

**Comment by MoySantanaV** [comment]
> How can I remove the standalone="yes" attribute? var builder = new xml2js.Builder({ xmldec: { 'version': '1.0', 'encoding': 'UTF-8', 'standalone': false <---- remove } });


In my case I used:
const builder = new xml2js.Builder({xmldec: { version: '1.0', encoding: 'UTF-8' }});

if you console.log the builder you will see all the options and change them as you need.

`Builder {
  options: {
    explicitCharkey: false,
    trim: false,
    normalize: false,
    normalizeTags: false,
    attrkey: '$',
    charkey: '_',
    explicitArray: true,
    ignoreAttrs: false,
    mergeAttrs: false,
    explicitRoot: true,
    validator: null,
    xmlns: false,
    explicitChildren: false,
    preserveChildrenOrder: false,
    childkey: '$$',
    charsAsChildren: false,
    includeWhiteChars: false,
    async: false,
    strict: true,
    attrNameProcessors: null,
    attrValueProcessors: null,
    tagNameProcessors: null,
    valueProcessors: null,
    rootName: 'root',
    xmldec: { version: '1.0', encoding: 'UTF-8' },
    doctype: null,
    renderOpts: { pretty: true, indent: '  ', newline: '\n' },
    headless: false,
    chunkSize: 10000,
    emptyTag: '',
    cdata: false
  }
}`

if you use another option like standalone: false || null this just will add the atribute to the options but it wont remove the string.
