### ISSUE TITLE
Builder with attributes?

### ISSUE THREAD

**Issue by michaelmcmillan** [Leonidas-from-XIV/node-xml2js#135]
Hi! I was wondering if the Builder supports attributes in tags? The docs does say nothing about it.
- M

**Comment by gigmig** [comment]
Thanks for this @nabeel-ahmad , documentation should definitely include this in builder usage

**Comment by Leonidas-from-XIV** [comment]
Pull requests welcome.

**Comment by ericsciple** [comment]
PR https://github.com/Leonidas-from-XIV/node-xml2js/pull/373

**Comment by simachewh** [comment]
Also if you want to add a text node to the element you're adding an attribute for, this should work. 
`{ room : { $: { id : "1000202" }, "_" : "Living room" } }`
it should give `<room id="1000202"> Living room </room>`

**Comment by mamayadi** [comment]
and how to make this in JSON format to give me XML like this:
<balisename xmlns:xlink="http://www.w3.org/1999/xlink">

**Comment by mamayadi** [comment]
this is the solotion if it could help any one:
`$: { 'xmlns:xlink': "http://www.w3.org/1999/xlink" }`
