### ISSUE TITLE
Unclosed root tag

### ISSUE THREAD

**Issue by victorkurauchi** [Leonidas-from-XIV/node-xml2js#147]
I know this issue was already mentioned at #51 

I'm trying to obtain an xml from external url. The first time i tried, it worked, but now i'm getting this error: 'Unclosed root tag'

Code:

```
xml = "http://foo.com/foo.xml"

request = http.get xml, (response)->
  response.on 'data', (chunk) -> 
    console.log('body: ' + chunk)

    parser = new xml2js.Parser()
    parser.parseString chunk, (err, result)->
      throw err if err

      console.log result
```

At .parseString() i'm not able to proceed, because the error occurs. Anyone knows something to solve that? 

I appreciate.

**Comment by manivinesh** [comment]
@victorkurauchi i am facing similar issue. May i know how you resolved it?
