### ISSUE TITLE
Elements with only a text node child are treated differently

### ISSUE THREAD

**Issue by Spetnik** [Leonidas-from-XIV/node-xml2js#162]
In the example of 

``` xml
<root><a>1</a><b hasattr='yes'>2</b></root>
```

elements "a" and "b" will be treated differently. The value of "a" will be just the text content as a single array element but the "b" will have an object in an array and that object will contain the children.

i.e: 

``` javascript
{
  a: [ '1' ],
  b: [ {
     _: '2',
    '$': { hasattr: 'yes' }
  } ] 
}
```

This is inconsistent and causes issues in the event where we don't know (and don't care) about anything other than the text value of the element. In this case, we would have to check the type of element[0] to see whether it is a string or an object.

Wouldn't it make more sense for the result to be:

``` javascript
{ a: [{
    _:  '1'
  }],
  b: [ {
    _: '2',
    '$': { hasattr: 'yes' }
  } ]
}
```

-AJS

**Comment by Leonidas-from-XIV** [comment]
There is always a balance between simplicity of the resulting object and uniformity of the input. Version 0.2 addressed the most annoying case, but you are right, this behaviour can be annoying when dealing with XML that may or may not have attributes.

If you like, you can send a PR and I'd be willing to add it as an non-default option for the parser.

**Comment by jcsahnwaldt** [comment]
Set parser option `explicitCharkey: true`.

Example:
```js
const xml2js = require('xml2js');

let parser = new xml2js.Parser({
  explicitCharkey: true
});

let xml = `<root><a>1</a><b hasattr='yes'>2</b></root>`;

parser.parseString(xml, (err, res) => {
  console.dir(res, {depth: null});
});
```
Output:
```js
{ root: 
   { a: [ { _: '1' } ],
     b: [ { _: '2', '$': { hasattr: 'yes' } } ] } }
```

**Comment by jcsahnwaldt** [comment]
I think this can be closed.
