### ISSUE TITLE
Add option for building empty tags

### ISSUE THREAD

**Issue by joshball** [Leonidas-from-XIV/node-xml2js#166]
Like to have an option in the builder to output empty tags as either:
    `<Children></Children>`
or 
`<Children />`

**Comment by Leonidas-from-XIV** [comment]
Sure, this is probably an easy PR. Feel like submitting one?

**Comment by phamdt** [comment]
+1

**Comment by jcsahnwaldt** [comment]
There's an `allowEmpty` option in xmlbuilder now, which users can simply add to the `renderOpts` in xml2js:

Quote from https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string :

If `allowEmpty` is set, empty nodes will not be self-closed, for example:

```js
root.end({ allowEmpty: true });
// with allowEmpty: true
<?xml version="1.0"?><root></root>
// with allowEmpty: false
<?xml version="1.0"?><root/>
```

**Comment by jcsahnwaldt** [comment]
```js
const xml2js = require('xml2js');

function test(renderOpts) {
  let js = { root: {} };
  let builder = new xml2js.Builder({ renderOpts });
  let xml = builder.buildObject(js);
  console.log(xml);
}

test({allowEmpty: true});
test({allowEmpty: false});
```
Output:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root></root>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root/>
```

**Comment by Leonidas-from-XIV** [comment]
Thanks, looks like that takes care of it.
