### ISSUE TITLE
Stack traces from event handler code get suppressed by xml2js

### ISSUE THREAD

**Issue by CandleCandle** [Leonidas-from-XIV/node-xml2js#172]
```javascript
var xml2js = require('xml2js');
var util = require('util');
var parser = xml2js.Parser();
var done = false;
var count = 0;

console.log('starting');
parser.on('end', function(result) {
    console.log(util.inspect(result, {depth: 5}));
    functionThatDoesNotExist(result);
    console.log('finished successfully');
    done = true;
});
parser.parseString('<valid_xml attr="val" />');
(function wait() {
    if (!done) {
        if (count > 2) done = true;
        count = count + 1;
        setTimeout(wait, 1000);
    }
})();
```
## Expected:
A stack trace telling me that I've got an error in my javascript.
## Actual:
No error message, silent failure.

## Discussion:
The above test case runs for a 3 seconds and exits. Commenting out the functionThatDoesNotExist line causes it to print 'finished successfully'. 

The error that is generated by the fact that there is an undefined function is caught by one of the catch blocks in xml2js and suppressed. This causes problems when:
* unit testing: 
 * The error message for a failure is suppressed, leading to a test that passes when it should fail.
 * The error is suppressed and the asynchronous test gets a timeout, again, unhelpful.
* general development: "where did my error message go?"

**Comment by Leonidas-from-XIV** [comment]
You are completely right. I see you've been working at it, that's great! When you're done, send it to me as PR and I'll merge it and create a new release.

(As a hint, you can start `cake build` in a terminal, which automatically monitors & compiles the CoffeeScript to JavaScript in the background, so you never forget to compile)
