### ISSUE TITLE
Need Line Number

### ISSUE THREAD

**Issue by EToreo** [Leonidas-from-XIV/node-xml2js#175]
I need to know the line number of any node in the file, is there any option I am missing, or can you add to the information returned about a node?

**Comment by Leonidas-from-XIV** [comment]
There is no such option, currently. I also don't plan to add such, since I don't consider the line number a property of the data but rather of the particular XML serialization. Sorry.

**Comment by EToreo** [comment]
That is too bad.  I think many clients would enjoy having that information.  I know its a requirement for my application.  I was able to find a way to get xmldoc to do it, and its working great there: https://github.com/nfarina/xmldoc/issues/14

**Comment by samgensburg** [comment]
Hi, I wanted to reopen this issue. I understand your philosophical position, but, practically speaking, I need this to provide proper validation for my API.

Simply put, imagine a client submits an xml file with complex validation errors, and they need to add a <value-name> field to one of several <item-type> objects. How am I supposed to message this to them in my response? I would like to say, "The <item-type> object on line xxx requires a <value-name> field." However, I'm not sure how to message this without line numbers. Are there any alternatives? This seems like a fairly normal use case.
