### ISSUE TITLE
try-catch and v8 performance

### ISSUE THREAD

**Issue by skoranga** [Leonidas-from-XIV/node-xml2js#176]
These try-catch statements https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L362-L366 & https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L437-L453 will make these functions `onclosetag` and `parseString` unoptimized in v8.

**Comment by Leonidas-from-XIV** [comment]
Thanks… but what do you propose to do instead?

(Thinking of it, it would be neat to have a performance benchmark)

**Comment by skoranga** [comment]
Sure, if you need I can work on benchmarking this.

Separating try-catch logic into a small function and calling that function instead will help.
This is what I found as reference - https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax & http://www.html5rocks.com/en/tutorials/speed/v8/#toc-topic-compilation

**Comment by Leonidas-from-XIV** [comment]
Great! If you would like to make a benchmark, so we can see if there is a tangible difference, I'm all for improving the performance in a cheap and mostly easy way.! Thanks for the links, I have no problem defining some external helpers for this, but then I'd like to see at least a measurable improvement :-)

**Comment by skoranga** [comment]
Here is my take on benchmarking integration - https://github.com/skoranga/node-xml2js/tree/master/benchmark. Seeing around 1000+ ops/sec improvement in node@0.10.36 but almost nothing in node@0.12

**Comment by Leonidas-from-XIV** [comment]
Do I read it right that 0.12 is significantly slower than 0.10?

**Comment by skoranga** [comment]
sorry looks like i am not testing parseString API properly. Fixing the tests now.

**Comment by skoranga** [comment]
Hi @Leonidas-from-XIV, updated the benchmarking https://github.com/skoranga/node-xml2js/tree/master/benchmark. Actually not seeing significant difference now. 

It's up to you, you can close this issue if you find results not satisfying. 

thanks

**Comment by jcsahnwaldt** [comment]
I guess this can be closed.
