### ISSUE TITLE
Writing CDATA failed on non-array properties

### ISSUE THREAD

**Issue by hail2u** [Leonidas-from-XIV/node-xml2js#178]
`Builder({cdata:true})` introduced in v0.4.5 does not work properly on a sub property that is not Array.

Test code:

```javascript
var xml2js = require('xml2js');

console.log(new xml2js.Builder({
  cdata: true
}).buildObject({
  'foo': {
    'bar': 'baz & qux'
  }
}));
```

Outputs:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<foo>
   <bar>baz &amp; qux</bar>
</foo>
```

Should be:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<foo>
   <bar><![CDATA[baz & qux]]></bar>
</foo>
```

I think calling `wrapCDATA` at [Case #5](https://github.com/Leonidas-from-XIV/node-xml2js/blob/208dff5784dfed5951d4bebe9c4071935cfabbdc/src/xml2js.coffee#L161-L163) is also required for writing CDATA properly.

**Comment by wr404274848** [comment]
when Builder({ headless: true, cdata: true }) with headless and cdata to true,then writing CDATA does't work
