### ISSUE TITLE
Can I do xpath queries on the XML with library

### ISSUE THREAD

**Issue by monkeyfdude** [Leonidas-from-XIV/node-xml2js#180]
I need to search an element. I did not see xpath queries in README

Can I do xpath queries on the XML with this  library or

Do I need to convert to JSON and then search the element in it?

**Comment by Leonidas-from-XIV** [comment]
You got the right conclusion: There is no XPath or CSS selector support in the library. You can couple it with some other solutions to get it, I suppose.

**Comment by monkeyfdude** [comment]
Ok thanks!
