### ISSUE TITLE
assign undefined to empty tag

### ISSUE THREAD

**Issue by scopsy** [Leonidas-from-XIV/node-xml2js#183]
Is it possible to assign the empty xml tags to an undfined value? when putting emptyTag: undefined the parser will not parse the items and will not generate them in the json file. However i need it to still show the propery "foo": undefined

anyway around this ?

**Comment by Leonidas-from-XIV** [comment]
You could delete the offending tags from the resulting object, I don't see much use into special casing for this single requirement.

**Comment by scopsy** [comment]
Im parsing a large xml document and saving it to mongodb. The thing is that i dont want null values saved. 

But thanks anyway...
