### ISSUE TITLE
new Builder raises "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by pellekrogholt** [Leonidas-from-XIV/node-xml2js#184]
# versions

package.json:"

    "xml2js": "0.4.5",

and with master 208dff5784dfed5951d4bebe9c4071935cfabbdc

# problem

ok i had a use case where i both needed a to parse and build

      var xml2js = new xml2js.Parser({async: false});
      var builder = new xml2js.Builder();

raised

      var builder = new xml2js.Builder();
                    ^
    TypeError: undefined is not a function

changing the order 

      var builder = new xml2js.Builder({});
      var xml2js = new xml2js.Parser({async: false});

works(TM)

ok pardon me if its not an error or just me not reading the fine docs carefully enough but I had a struggle with it.

**Comment by Leonidas-from-XIV** [comment]
Shadowing the `xml2js` module with an instance of the parser is indeed *unfortunate* (so even if you reverse the order, its still not a good idea).

I just checked whether the docs suggest writing such code, because that would be embarrassing. They fortunately don't, so I'm closing this issue.
