### ISSUE TITLE
Support for root attributes in builder

### ISSUE THREAD

**Issue by sylbal** [Leonidas-from-XIV/node-xml2js#186]
Hi,
I'd need to add some attributes on the root node when building my XML document. Apparently xmlbuilder-js is supporting this, any way to achieve it or this would require a new feature ?

Regards,

**Comment by evliu** [comment]
+1 ran into the same issue today

**Comment by evliu** [comment]
ended up including xmlbuilder in my project since it works correctly. seems like something is getting lost in the passthrough from xml2js buildObject. instead of getting a root attribute, i get a child element with the list decorator in the name:
```xml
<test><@user>yes</user></test>
```
instead of
```xml
<test user="yes"></test>
```
doesn't matter if the decorator is $ or @

**Comment by Leonidas-from-XIV** [comment]
Yeah, that should be fixed, there's a bug in there somewhere. I haven't done much with the Builder that's mostly work of @jacksenechal.

**Comment by loge5** [comment]
Ran into same issue, found a solution:

```javascript
var xml2js = require('xml2js');
var builder = new xml2js.Builder({
    rootName: 'myroot'
});
var xml = builder.buildObject({
    $: {
        someAttr: 'foo'
    },
    firstChild: "bar"
});
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<myroot someAttr="foo">
  <firstChild>bar</firstChild>
</myroot>
```

**Comment by jcsahnwaldt** [comment]
In xml2js 0.4.19, this also works without the `rootName` option:

```javascript
const xml2js = require('xml2js');
const builder = new xml2js.Builder();

let js = {
  root: {
    $: {
      foo: 'bar',
    }
  }
};

let xml = builder.buildObject(js);
console.log(xml);
```
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root foo="bar"/>
```

**Comment by jcsahnwaldt** [comment]
I think this issue can be closed.

**Comment by evliu** [comment]
Probably, haven’t touched it for 3 years. Thx
