### ISSUE TITLE
Can't handle the exception when parseString takes a "undefined"

### ISSUE THREAD

**Issue by jesusjzp** [Leonidas-from-XIV/node-xml2js#193]
In this example:
```javascript
var fs = require('fs'),
    xml2js = require('xml2js');

var parser = new xml2js.Parser();
fs.readFile(__dirname + '/foo.xml', function(err, data) {
    parser.parseString(data, function (err, result) {
        console.dir(result);
        console.log('Done');
    });
});
```
Unintentionally when I give a wrong file path, the function `parseString` will take an `undefined` instead of data string, and the parser didn't handle the exception here:
[https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L439](https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L439)
```javascript
str = str.toString();  // str is undefined, throw an exception
if (str.trim() === '') {
this.emit("end", null);
  return true;
}
```
And the server stop with the error below:
```shell
c:\Users\zhipengj\WebstormProjects\psme\node_modules\xml2js\lib\xml2js.js:444
      str = str.toString();
                ^
TypeError: Cannot call method 'toString' of undefined
    at Parser.exports.Parser.Parser.parseString (c:\Users\zhipengj\WebstormProjects\psme\node_modules\xml2js\lib\xml2js.js:444:17)
    at Parser.bind [as parseString] (c:\Users\zhipengj\WebstormProjects\psme\node_modules\xml2js\lib\xml2js.js:6:59)
    at service.parseFile (c:\Users\zhipengj\WebstormProjects\psme\services\services.js:83:12)
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)

Process finished with exit code 8
```

I think it could be gracefully if we could handle the exception without crashing the server.

**Comment by jesusjzp** [comment]
I have created a pull request for this issue: [https://github.com/Leonidas-from-XIV/node-xml2js/pull/194](https://github.com/Leonidas-from-XIV/node-xml2js/pull/194)

**Comment by Leonidas-from-XIV** [comment]
Well you should definitely always check whether you read sensible data. `xml2js` cannot check for every eventuality. In your example, `err` would be populated with some indication that an error happened, so you should check for that before pushing the (invalid) data to `xml2js`.

Generally: garbage in = garbage out.
