### ISSUE TITLE
Support for multiple root nodes?

### ISSUE THREAD

**Issue by sjlynch** [Leonidas-from-XIV/node-xml2js#197]
When parsing the following string, the xml object which comes back won't contain the second root node. Is there some way to enable this or does this feature (is it a feature?) not exist?

"\<root>Hello xml2js!\</root>\<root>Hello again xml2js\</root>"

**Comment by Leonidas-from-XIV** [comment]
Yes, since only the first part is valid XML, the rest is just random data following. XML can only have one root element. I don't even know whether sax-js even passes the second part to xml2js.

**Comment by sjlynch** [comment]
Ok thanks for the reply. I have an unusual use-case where a program outside of my control appends results without making sure the xml is well-formed, so it creates a bunch of root nodes. It makes sense that malformed XML cannot be parsed. I'll find a workaround.

Thanks!

**Comment by Leonidas-from-XIV** [comment]
You could wrap it in a common root node. If there is only one sub-root node, you can pop off the common root node, if not you just have two (or more) subnodes from the common root.

**Comment by sjlynch** [comment]
That's a good idea. 

The problem is that I am communicating with a program via the local filesystem (I don't have a choice here, haha..) so results are appended to an existing xml file that I'm watching for changes made by that program. So the data appended at the end is never accessible via xml2js. So I'm currently just wiping the file clean whenever it's changed by the external program and that allows me to read in the new data the next time it's appended. Hacky, but it works.

**Comment by Leonidas-from-XIV** [comment]
It is not possible to support every exotic use case out of the box, sorry.

**Comment by phawxby** [comment]
Digging this back up from nearly 5 years ago, I've got a similar use case. The Adobe Analytics data insertion API does not conform to the XML spec.
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/data-insertion-api/sample_code/r_sample_http_post.md

While no sample is provided on a request failure you get this back.
```
<?xml version="1.0" encoding="UTF-8"?>
<status>FAILURE</status>
<reason>NO account</reason>
```

I'm trying to figure out a reliable way to fix this before parsing, I'm thinking wrapping may be the best solution. However having "fragmented" parsing would be a great addition to the library. There's prior examples of this kind of parsing in the C# XmlReader.
https://stackoverflow.com/a/13809176/468214
