### ISSUE TITLE
Unable to parse CakePHP error output (HTML)

### ISSUE THREAD

**Issue by unphased** [Leonidas-from-XIV/node-xml2js#201]
I have some automated test systems that have to interface with PHP and basically I have been using xml2js to try to handle the output made with the default PHP error message templates. 

For example I recently became really frustrated by the fact that I have to copy out the URL request and run it in a browser *manually* in order to actually view the content of the error emitted by PHP. 

It turns out that while some of the structure of this HTML is captured, most of the content of the information is stripped out for some reason. 

I understand that this type of output (it tends to contain lots of pre's with lots of code inside, and considering that this is PHP it may well have some HTML inside of THAT as well (though not in my particular use case)) is *really* bad, but I think I can still expect a decent XML parser to handle it. 

So I'm not really looking for a fix or anything, I'm just curious if anyone else has tried something similar and has some tips. 

[Here is an example](http://pastebin.com/raw.php?i=RaQRgYDe) (that e.g. pastebin's HTML syntax highlighter has no problem parsing). For starters, in this example, in the output some simple `<b>` tags are just taken out, nowhere to be found. So 

```
[<b>APP/Controller/Controller.php</b>, line <b>1193</b>]
```
turns into `[, line ]`

**Comment by Leonidas-from-XIV** [comment]
Is your input well formed XML?

**Comment by unphased** [comment]
It is close to being well-formed. running tidy on it fixes a few small items, this is what it had to say: 

```
$ tidy deleteme > deletemetidy  
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: missing </pre> before <div>
line 96 column 48 - Warning: inserting implicit <pre>
line 97 column 1 - Warning: missing </pre> before <div>
line 1188 column 48 - Warning: inserting implicit <pre>
line 1 column 1 - Warning: <!DOCTYPE> isn't allowed after elements
line 1191 column 1 - Warning: discarding unexpected <html>
line 1 column 1 - Warning: <head> isn't allowed in <body> elements
line 1 column 1 - Warning: <meta> isn't allowed in <body> elements
line 1 column 1 - Warning: <title> isn't allowed in <body> elements
line 1 column 1 - Warning: <link> isn't allowed in <body> elements
line 1 column 1 - Warning: </head> isn't allowed in <body> elements
line 1199 column 1 - Warning: discarding unexpected <body>
line 1203 column 65 - Warning: <br> element not empty or not closed
line 1206 column 76 - Warning: <br> element not empty or not closed
line 1 column 1 - Warning: content occurs after end of body
line 96 column 48 - Warning: trimming empty <pre>
line 1188 column 48 - Warning: trimming empty <pre>
Info: Doctype given is "-//W3C//DTD XHTML 1.0 Transitional//EN"
Info: Document content looks like XHTML 1.0 Transitional
18 warnings, 0 errors were found!


To learn more about HTML Tidy see http://tidy.sourceforge.net
Please send bug reports to html-tidy@w3.org
HTML and CSS specifications are available from http://www.w3.org/
Lobby your company to join W3C, see http://www.w3.org/Consortium
```
When I send [**the result of feeding my input through html-tidy**](http://pastebin.com/raw.php?i=FeLLndsr) into the w3.org xml validator it passes (`This document was successfully checked as XHTML 1.0 Transitional`), the output from xml2js is acceptable for this. 

I think there is no real issue or problem here, essentially xml2js isn't meant to be as resilient to crappy input as a browser is.

**Comment by Leonidas-from-XIV** [comment]
> I think there is no real issue or problem here, essentially xml2js isn't meant to be as resilient to crappy input as a browser is.

Well, xml2js parses XML, whereas a browser tries its best to parse HTML, which is much more lenient than XML, so you are comparing apples to oranges. xml2js should be able to parse XHTML just fine, since it is XML and should also work on the XML serialization of HTML5. Beyond that, it will probably barf and is definitely not the right tool for the task.
