### ISSUE TITLE
Parsing OFX xml missing closing tags error

### ISSUE THREAD

**Issue by GradyD** [Leonidas-from-XIV/node-xml2js#203]
I have an OFX file, example: https://github.com/GradyD/banking.js/blob/master/test/fixtures/sample.ofx.

I removed the header without any issues but when I try,
```
var parser = new parseString.Parser(); // where parseString is the require of xml2js
JSON.parse(JSON.stringify(parser.parseString(ofx, function(err, result) {
  // console.dir("OFX FILE:" + ofx);
  console.dir("ERROR:" + err);
  console.dir("RESULT:" + result);
})));
```

I always get the same error,
'ERROR:Error: Unexpected close tag\nLine: 6\nColumn: 15\nChar: >'

When I manually add the closing tags it starts to progress the file, but keeps getting hung up as more items are missing the closing tag. The XML file I get from an ajax call does not have ending tags for every line and I would prefer to not hand edit the file everytime, is there a way I can still parse this out? 

Currently the project is using 'xml2json', which I am having issues installing on my windows desktop so I am trying to transfer to 'xml2js'. I could not test but because there is not an open issues on the parent repo I am assuming that xml2json is currently working.

Any help would be appreciated!

Thanks

**Comment by Leonidas-from-XIV** [comment]
> When I manually add the closing tags it starts to progress the file, but keeps getting hung up as more items are missing the closing tag. The XML file I get from an ajax call does not have ending tags for every line and I would prefer to not hand edit the file everytime, is there a way I can still parse this out? 

This is not an XML file, so no, it can't be parsed that way. You need to turn it into a well-formed XML file before attempting any parsing. You could try running HTML Tidy on it before parsing, but no idea if this will work in all cases.
