### ISSUE TITLE
how to ignore empty tags?

### ISSUE THREAD

**Issue by tsofist** [Leonidas-from-XIV/node-xml2js#207]
I know that there is an option emptyTag, I understand that you can specify null or undefined, but what if I do not need these tags?
I would be grateful for your help in this matter!

**Comment by Leonidas-from-XIV** [comment]
If you don't need the tags, you can remove them from the resulting object.

**Comment by tsofist** [comment]
Imagine a large xml document with a complex structure. I'll have to get around the whole document to clean the properties whose values correspond to the value "emptyTag". But it is much simpler and, most importantly, more effective not to add such properties of the resulting object.

**Comment by Leonidas-from-XIV** [comment]
It is not particularly more effective, since the SAX parser *will* traverse the whole XML anyway, only to ignore the tags on a higher level.

**Comment by tsofist** [comment]
I understand it. But xml2js have the opportunity "on track" to cut items such as, I would have to bypass the document again.
The fact that the browser side, I use a tool with similar functionality, and I got the same result xml2js. However, browser-based tool exclude empty tags by default.
Thank you for your response.
I will use post-processing results obtained from xml2js to maintain uniformity.

**Comment by tayden** [comment]
If it helps anybody else, I wrote a post processing function that removes empty values from the resulting json.

```javascript
/**
 * Recurse through a JSON structure and remove array values equal to "" and object key: value pairs where the value === "".
 * Used to remove empty XML tags from the output JSON created by koaXmlBody.
 *
 * @param {Object[]} val The JSON structure
 * @returns {Object[]} The new JSON structure with empty values removed
 */
function removeEmptyValues(val) {
  if (Array.isArray(val)) {
    return val.reduce((res, cur) => {
      if (cur !== "") {
        return [...res, removeEmptyValues(cur)];
      }
      return res;
    }, []);
  } else if (Object.prototype.toString.call(val) === "[object Object]") {
    return Object.keys(val).reduce((res, key) => {
      if (val[key] !== "") {
        return Object.assign({}, res, { [key]: removeEmptyValues(val[key]) });
      }
      return res;
    }, undefined);
  }
  return val;
}

```
