### ISSUE TITLE
Getting particular node name as array type

### ISSUE THREAD

**Issue by dsamit** [Leonidas-from-XIV/node-xml2js#210]
I am trying to parse a xml string to json in such a way that a node having particular name should always be an array type.
There is one option "explicitArray " while parsing.
But it works for all of the elements.
I need array type conversion for a node having particular name.
I am not able to proceed for this.
Please help me out.
Any help from you people matters a lot for me and project development .

**Comment by Leonidas-from-XIV** [comment]
What is wrong with `explicitArray`? In my opinion that is a reasonable setting in any case.

**Comment by dsamit** [comment]
explicitArray is working fine. But it does conversion to array for all nodes.
I want a node with particular specific name should be converted to array and rest as it does.

**Comment by Leonidas-from-XIV** [comment]
Why is converting all nodes an issue for you? I am actually thinking that explicitArray could be the default setting in a future release.

**Comment by dsamit** [comment]
converting all nodes as array fine.
But is there any way to force a particular node to be converted as array. Not all nodes.

**Comment by Leonidas-from-XIV** [comment]
No, there is not.

**Comment by dsamit** [comment]
If you will tell me the point from where conversion type is being controlled. then i can move further.

**Comment by Leonidas-from-XIV** [comment]
You could just use `explicitArray`. I don't know what you want to do "further", there are no other steps required.

**Comment by dsamit** [comment]
explicitArray is a standard conversion for all nodes.
I want type conversion can be modified for a particular node

**Comment by Leonidas-from-XIV** [comment]
Use `explicitArray` and do the conversion in your application.

**Comment by dsamit** [comment]
ok thanks for your time

**Comment by eych** [comment]
The main use case for this is when a particular node usually has a list of values, but in rare cases, it's only one value. So, when using `explicitArray: false`, it's usually converted to an array, but in a few odd cases, it's not an array.

My application is expecting it to always be an array and it's awkward to check each time if it is, in fact, an array for each item and handle the value differently if it's not. A more convenient way would be to tell xml2js to always create arrays for that particular node.

**Comment by Leonidas-from-XIV** [comment]
Then it is a bug in `explicitArray` and should be fixed.

**Comment by eych** [comment]
No, this is not a bug. It works correctly according to the behaviour I marked with bold below:

> explicitArray (default: true): Always put child nodes in an array if true; **otherwise an array is created only if there is more than one.**

Consider this XML example:
```
<items>
  <item>
    <serviceFlag>
      <key>msvWithOverageCharges</key>
      <value>Identify mobile share value SDGs with Overage to trigger appropriate content on Plan configurator page</value>
    </serviceFlag>
    <serviceFlag>
      <key>isDoubleDataSDG</key>
      <value>To test the removal message when user removes double data SDG from their account.</value>
    </serviceFlag>
  </item>
  <item>
    <serviceFlag>
      <key>msvWithOverageCharges</key>
      <value>Identify mobile share value SDGs with Overage to trigger appropriate content on Plan configurator page</value>
    </serviceFlag>
  </item>
</items>
```

With `explicitArray: false` the first item will have an array in `serviceFlag` while the second item will have a hash in the same key. Which will require the application logic to have extra code to handle this correctly which could be easily avoided if I can just tell xml2js to always create arrays for the node `serviceFlag` while using `explicitArray: false` behaviour for everything else.

**Comment by Leonidas-from-XIV** [comment]
But then your application will fail if the user supplies just one item since suddenly the children of array are not an array. So it is better to use `explicitArray` instead of having the code crash on unexpected input.

**Comment by eych** [comment]
Not sure I follow. If the `explicitArray: false` behaviour is kept as it is and a new setting is added with a signature like this: `explicitArrayNodes: ['serviceFlag']` then my application will always have an array in `serviceFlag`, even if it's just one element.

**Comment by Leonidas-from-XIV** [comment]
Yes, but the other nodes where you expect an array, like `items` would turn into a single element if you get passed just a single `item` by whoever supplies the XML thus breaking your code if you expect to iterate over items.

**Comment by JayAhn2** [comment]
@eych Have you found any solution about this issue?

Thanks.
