### ISSUE TITLE
processor "parseNumbers" is not working

### ISSUE THREAD

**Issue by dsamit** [Leonidas-from-XIV/node-xml2js#212]
Hi,
I am trying to parse a xml string and convert it to json. 

The xml string contains some numbers text.

When i was passing this xml string to parseString function with options parseNumbers:true 
then also its giving json string with double quoted numbers value.
which i don't want.

**Comment by Leonidas-from-XIV** [comment]
Can you post a working example?

**Comment by Alino** [comment]
I got the same issue, using option parameter **parseString: true** does nothing :(

**Comment by dsamit** [comment]
Hi @Alino, 
I got rid of this issue by doing this.
step 1: define a function named of any name for my case it is 'parseNumbers'
            function parseNumbers(name){
	    if (!isNaN(name)) {
	      name = name % 1 === 0 ? parseInt(name, 10) : parseFloat(name);
	    }
	    return name;
	}
step 2: call the function parseString with an additional parameter 'valueProcessors' like this
            parseString(xmlData, {valueProcessors: [parseNumbers]}, function (err, result) {    
	           console.log(JSON.stringify(result));	    
	    });

Note: Here for parameter key valueProcessors i have given value parseNumbers which is the name of the function which you declared using step 1.

**Comment by Alino** [comment]
@dsamit thank you, it works well for me. :)

**Comment by wattgo** [comment]
Setting 'parseNumbers' to 'true' still does nothing but xml2js actually exports the 'parseNumbers' function, so you can do :  
```javascript
var xml2js = require('xml2js');
var options = {
  valueProcessors: [ xml2js.processors.parseNumbers ]
}
xml2js.parseString(str, options, callback);
```

**Comment by Leonidas-from-XIV** [comment]
Yes, that's exactly how it is supposed to be used (see [example in README](https://github.com/Leonidas-from-XIV/node-xml2js#processing-attribute-tag-names-and-values)). Closing this then.
