### ISSUE TITLE
In browser usage

### ISSUE THREAD

**Issue by bguiz** [Leonidas-from-XIV/node-xml2js#215]
I'd like to be able to use this in the browser, without having to use browserify.

Could we UMD-ise each of the modules, or just the compiled JS file (`lib/xml2js.js`)?

**Comment by Leonidas-from-XIV** [comment]
Sounds good, but I would like to have a way to test it in at least one browser via Travis CI or similar tools, so that it won't break down at some point.

**Comment by bguiz** [comment]
Yup, the easiest way to do this looks like it would be to wrap
`lib/xml2js.js` (the output file) in an IIFE to do the UMD operations.
Something like.


```javascript
// if browser
window.xml2js = {};
var exports = window.xml2js;
```
W: http://bguiz.com

**Comment by Leonidas-from-XIV** [comment]
Yes, but I still need a way to run the unit tests in a browser-like environment.

**Comment by Leonidas-from-XIV** [comment]
I believe with the recent changes, `xml2js` should be working fine in the browser.
