### ISSUE TITLE
Known array values

### ISSUE THREAD

**Issue by danielb2** [Leonidas-from-XIV/node-xml2js#216]
When using option `explicitArray` is there anyway to specify specific attributes to always be treated as an array?  For example, it makes sense for pluralized properties to be arrays.

`errors` vs `error`.  Would be nice if errors was an array.

Otherwise just being able to specify properties which are known to be arrays

**Comment by Leonidas-from-XIV** [comment]
There is no such functionality at the moment. Personally, I think `explicitArray = false` is a mistake, all new code should use `explicitArray`.

**Comment by danielb2** [comment]
Does this mean you would not accept a PR for the functionality I'm asking about?

To only have arrays makes parsing the resulting JSON inconsistent with the intended hierarchy in a document.

**Comment by firefoxNX** [comment]
+1

@danielb2 - What approach did you take to make certain elements as an array?

@Leonidas-from-XIV  - With explicitArray = true the JSON has way too many square brackets and is not readable at all

```
{
    "bananas": [
        {
            "banana": [
                {
                    "bananaId": [
                        "24281"
                    ],
                    "country": [
                        "USA"
                    ],
                    "name": [
                        "Minions love Bananas"
                    ],
                    "status": [
                        "ACTIVE"
                    ],
                    "version": [
                        "0"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by danielb2** [comment]
@firefoxNX  I ended up taking another library and modifying it to what I want. It sounded like this project has some weird ideas about doing that and I didn't get an answer about my PR question.

I hadn't checked it in, but did for you: https://github.com/danielb2/node-xml2json/tree/forceArray

The syntax is just `forceArray: ['error']`  which would mean that any property called `error` is now an array

I see I've left some debug printing in my code, so be aware of that.

**Comment by firefoxNX** [comment]
Thanks @danielb2 but I don't see any references to forceArray in the code?

**Comment by danielb2** [comment]
Did you check the commits I made on my branch? https://github.com/danielb2/node-xml2json/commits/forceArray

**Comment by Leonidas-from-XIV** [comment]
> With explicitArray = true the JSON has way too many square brackets and is not readable at all

But at least it doesn't break your code, when suddenly an item is added where your code did not expect more than one item.

**Comment by Leonidas-from-XIV** [comment]
@danielb2, sorry for not answering your question, it somehow slipped my attention.

> Does this mean you would not accept a PR for the functionality I'm asking about?

That's right, I wouldn't want to include this, since it disagrees with how I think reliable code should be written.

**Comment by firefoxNX** [comment]
Thanks @danielb2 for providing the code but I am unable to use that because I cannot bring in native code dependencies. xml2js has a good approach as it uses pure javascript.
@Leonidas-from-XIV Thanks for the clarity.
For now I was able to create arrays in javascript code after parsing.

**Comment by danielb2** [comment]
> That's right, I wouldn't want to include this, since it disagrees with how I think reliable code should be written.

The purpose of the code I suggested is actually making an effort into making output MORE reliable in converting known arrays. 

Each use-case is different; there may be many small blurbs of XML for which the coder chooses to use forceArray: false and legitimately so. I tend to not remove options from others when I don't know their scope. Let others have the option to make their errors because ultimately you will also enable those who have legitimate use-cases ( I certainly know the issue, and it works for me ).  

Furthermore, to technically to justify the project as it stands in terms of reliability, you would want to provide an XML schema as an input in order to generate the JSON.

**Comment by Leonidas-from-XIV** [comment]
> The purpose of the code I suggested is actually making an effort into making output MORE reliable in converting known arrays.

I guess we disagree on whether consistent output is a good thing. Coming from Haskell, I do think that the type should be always the same, the most general, namely an array. Also, edge cases appear, like what to do when the programmer has specified that some tag is not in an array, but the XML that was passed in was an array?

> I tend to not remove options from others when I don't know their scope.

I don't do either. I am not removing the old behaviour. I am just not including more code that I then have to maintain and which behaviour I do not approve. I would like to have a great parser (which xml2js is not yet, agmittedly) but I do not want to have an assorted collection of pet features that can be just as well implemented on top of the output of xml2js, like @firefoxNX did.

> Furthermore, If you really wanted to justify the project in terms of reliability, you would want to provide an XML schema as an input in order to generate the JSON.

Honestly? I'd love such an PR! If you'd feel inclined to include schema-driven parsing, I think that'd be great.

Meanwhile, I'll close this issue.
