### ISSUE TITLE
How to mark a field as CDATA when building object to xml

### ISSUE THREAD

**Issue by flex1988** [Leonidas-from-XIV/node-xml2js#218]
```
var xml2js = require('xml2js');
var cBuilder = new xml2js.Builder({
    rootName: 'xml',
    cdata: true
});
var obj = {};
obj.code = 'FAIL';
var xml = cBuilder.buildObject(obj);
console.log(xml);
```
when i initialize the builder i have set the cdata as true,but it doesn't work.
so how to mark obj.code as CDATA when building a xml.
am i missed something?

**Comment by tiaoshi** [comment]
I got the same problem here. I passed `{ cdata: true }` to the `Builder` class, but the returned XML was not wrapped in CDATA. 

However, if my text contains a single `&` or `<` or `>`, it would be wrapped. 

My workaround is to change `xml2js.js: 191` to this:

```javascript
if (typeof child === 'string' && (_this.options.cdata || requiresCDATA(child))) { /* ... */ }
```

so that the text would be wrapped either when `cdata === true` or the text contains some special symbols.

**Comment by Leonidas-from-XIV** [comment]
This is by design. `CDATA` should only be generated if the data cannot be represented as normal text and has to be wrapped in `CDATA`.

**Comment by flex1988** [comment]
I wander if it is possible to modify the design to enable us to render CDATA like:
```
var obj = {};
obj.code = '#FAIL';
var xml = cBuilder.buildObject(obj);
console.log(xml);

<xml>
    <code>![CDATA[SUCCESS]]</code>
</xml>
```

**Comment by Leonidas-from-XIV** [comment]
What for? `CDATA` is only required when the data cannot be inserted in XML without escaping. If you just wrap normal, representable text in `CDATA` it is exactly equivalent to not wrapping it in `CDATA`:

From Wikipedia on `CDATA`:

> A CDATA section is merely an alternative syntax for expressing character data; there is no semantic difference between character data that manifests as a CDATA section and character data that manifests as in the usual syntax in which "<" and "&" would be represented by "&lt;" and "&amp;", respectively.

**Comment by flex1988** [comment]
@tiaoshi 
I have changed these lines to this:
```
if (typeof child === 'string' && _this.options.cdata && requiresCDATA(child)) {
                  if (child.indexOf('#') === 0) {
                    child = child.substring(1);
                  }
```
If a string with a '#' in head, it will be wrapped.
This works fine for me.
But im not sure if this is good or not.
Maybe i need to learn about CDATA in deep first.

**Comment by Leonidas-from-XIV** [comment]
Editing generated code is not a good idea to start with, if you really need to hack around in the code, you should better start at the source code.

**Comment by flex1988** [comment]
@Leonidas-from-XIV yeah,i edit source coffee code and the code above is after build.

**Comment by johnymonster** [comment]
The issue here is this: you state in the docs: `cdata (default: false): wrap text nodes in <![CDATA[ ... ]]>. Added in 0.4.5.`  However, that statement is not true and thus should be updated to say something along the lines of.  I really don't wrap anything in CDATA unless it needs to be wrapped in cdata...

**Comment by Leonidas-from-XIV** [comment]
Yes, that is indeed a failure of the documentation that should be amended. Thanks for pointing it out!

**Comment by johnymonster** [comment]
thanks!

**Comment by jamaica474** [comment]
Sometimes wrapping in CDATA is required, for no good reason for it. I'm implementing various integrations, one of them is with Indeed. 

> "Requirements: All job content must be inside CDATA sections to avoid issues processing your XML feed."
> https://www.indeed.com/intl/en/xmlinfo.html

https://www.indeed.com/intl/en/xmlinfo.html
Makes no tech sense, but still a deal-breaker for me.

**Comment by jonaser06** [comment]
> A veces se requiere envolver en CDATA, sin una buena razón para ello. Estoy implementando varias integraciones, una de ellas es con Indeed.
> 
> > "Requisitos: todo el contenido del trabajo debe estar dentro de las secciones CDATA para evitar problemas al procesar su fuente XML". 
> > [https://www.de hecho.com/intl/en/xmlinfo.html](https://www.indeed.com/intl/en/xmlinfo.html)
> 
> https://www.indeed.com/intl/en/xmlinfo.html No tiene sentido tecnológico, pero sigue siendo un factor decisivo para mí.

Hi, did you find a solution? I would like to make a fork of this, for me the use of cdata is also important regardless of the content that can escape the markup

**Comment by quentin-decre** [comment]
Hi folk, same issue here. Did you have a nice solution to force CDATA wrapping ?

**Comment by jamaica474** [comment]
Unfortunately no. I ended up using another package
