### ISSUE TITLE
Problems building XML with multiple properties with the same name

### ISSUE THREAD

**Issue by wOvalle** [Leonidas-from-XIV/node-xml2js#225]
I'm trying to build this xml from JSON:

```xml
<obj>
<innerObj val = '1'>
<or/>
<innerObj val = '2'>
</obj>
```

With the following JSON: 
```javascript
var obj = {
	innerObj: {$ : {val : 1}},
	or: '',
	innerObj : {$ : {val : 2}}
};
```
But it generates
```xml
 <innerObj val="2"/>
  <or/>
```
With the following code 
```javascript
var fs = require('fs'),
xml2js = require('xml2js');

var obj = {
	innerObj: {$ : {val : 1}},
	or: '',
	innerObj : {$ : {val : 2}}
};

console.log(new xml2js.Builder().buildObject(obj));
```
Any ideas?

**Comment by Leonidas-from-XIV** [comment]
> ```javascript
var obj = {
    innerObj: {$ : {val : 1}},
    or: '',
    innerObj : {$ : {val : 2}}
};```

This is an unordered collection, have you tried an ordered collection?

**Comment by Ava7** [comment]
@Leonidas-from-XIV I am not really sure what you mean by an ordered collection, but it seems that I also cannot find the way to preserve children elements sharing the same tag name. I did find the `explicitChildren` option for the `Parser` object, but I don't see how to achieve the same behavior when converting JavaScript objects into XML.

**Comment by tflanagan** [comment]
Have you tried:

```javascript
var xml2js = require('xml2js');
var obj = {
  innerObj: [
    { $: {val: 1} },
    { $: {val: 2} }
  ],
  or: ''
};

console.log(new xml2js.Builder().buildObject(obj));
```
Yields:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root>
  <innerObj val="1"/>
  <innerObj val="2"/>
  <or/>
</root>
```

Or:

```javascript
var xml2js = require('xml2js');
var obj = {
  innerObj: { $: {val: 1} }
  or: '',
  'innerObj ': { $: {val: 2} }
};

console.log(new xml2js.Builder().buildObject(obj));
```
Yields:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root>
  <innerObj val="1"/>
  <or/>
  <innerObj  val="2"/>
</root>
```

**Comment by Ava7** [comment]
@tflanagan Thanks for the examples, mate! I suppose I should re-read the docs about arrays and objects in JavaScript

**Comment by moezbhatti** [comment]
another way, which doesn't require you to keep track of how many spaces you've put into your value names

```js
var obj = {
  _: [
    { innerObj: { $: {val: 1} } },
    { or: '' },
    { innerObj: { $: {val: 2} } }
  ]
};
```

**Comment by hellogerard** [comment]
This worked for me:

```js
var obj = {
  innerObj: [
    { $: {val: 1} },
    { $: {val: 2} }
  ],
};
```

This did not work for me:

```js

another way, which doesn't require you to keep track of how many spaces you've put into your value names

var obj = {
  _: [
    { innerObj: { $: {val: 1} } },
    { innerObj: { $: {val: 2} } }
  ]
};
```

Which is a little weird. The latter is the syntax used in the automated tests, but did not work.
