### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by vko-online** [Leonidas-from-XIV/node-xml2js#230]
Any bower support?

**Comment by Leonidas-from-XIV** [comment]
Currently we don't support running xml2js in the browser, but I am not against it. I guess it depends on the availability of our dependencies.

**Comment by tflanagan** [comment]
I'm currently using xml2js (via Browserify) in the browser without issue.

**Comment by tflanagan** [comment]
Please see #231

**Comment by Leonidas-from-XIV** [comment]
Merged #231.

**Comment by tflanagan** [comment]
As of the latest version, xml2js works beautifully in the browser. I think this can be closed.

**Comment by ddcovery** [comment]
Then... Any bower support?

**Comment by tflanagan** [comment]
It looks like I can't read...

Bower not Browser. lol

Please see #251

**Comment by ddcovery** [comment]
Thanks a lot @tflanagan.

**Comment by Leonidas-from-XIV** [comment]
I've registered the package with bower now…

**Comment by pietersv** [comment]
@tflanagan   Might there be an example of how to include xml2js in the browser?
