### ISSUE TITLE
Error object is empty when parsing invalid xml

### ISSUE THREAD

**Issue by mark-r-m** [Leonidas-from-XIV/node-xml2js#233]
When using the util in node, I'm getting an empty error object with no details in it:

```javascript
var invalidXml = '<rootTag><startTagWithNoEnd>Data</mismatchedEndTag></rootTag>';
var xml2js = require('xml2js');
xml2js.parseString(invalidXml , function (err, result) {
  console.dir(err);
  console.dir(result);
});
```

Which gives this output

```javascript
{}
null
```

**Comment by tflanagan** [comment]
What version of xml2js are you using?

I'm getting an actual error message:

```
[Error: Unexpected close tag
Line: 0
Column: 51
Char: >]
undefined
```

**Comment by mark-r-m** [comment]
Thanks! I made a sily mitake - my logger code was doing a JSON.stringify(err) which in turn was printing "{}" - this must be an oddity of the JavaScript Error object.

I've updated my code to use a different logger method and it's working now - thanks!
