### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by maketroli** [Leonidas-from-XIV/node-xml2js#236]
I am trying to convert some XML to json

I have here this into a function

    var parseString = require('xml2js').parseString

```javascript
toXml = function(dataset) {
    var cancel, view, fillOpen;
    _.map(dataset, function(items) {
      return _.map(items, function(item) {
        parseString(item.XX_CANCEL, function(err, res) {cancel = res;});
        parseString(item.XX_VIEW, function(err, res) {view = res;});
        parseString(item['XX_FILL OPEN'], function(err, res) {fillOpen = res;});
        return item;
      });
    });
  }
```
and when I try to call it

```javascript
toXml(dataset).then(function(err, res) {
   console.log('>>>>>>>>>>>>>>>>>>items', res);
});
````
when I try to execute it, I get this error

    /home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/node_modules/babel-runtime/regenerator/runtime.js:493
            throw exception;
                  ^
    TypeError: Cannot read property 'toString' of null
        at Parser.exports.Parser.Parser.parseString ...

just for you to know, for example if I remove the `parseString(...)` and do 

    cancel = item.XX_CANCEL;

    console.log(cancel)
    logs ---> <element><element_type>BASIC_CHECKBOX</element_type><element_call/><element_content>1</element_content></element>

it logs that XML element, that is why I am doing it with the `parseString`, 

    cancel = parseString(item.XX_CANCEL, function(err, res) {cancel = res;});

so, what do you think is going on ?

All I need is to convert those XML elements into JSON.

**Comment by tflanagan** [comment]
I'm able to parse that string just fine.

```javascript
'use strict';

const parseString = require('xml2js').parseString;
const xmlString = '<element><element_type>BASIC_CHECKBOX</element_type><element_call/><element_content>1</element_content></element>';

parseString(xmlString, (err, result) => {
	if(err){
		console.error(err);

		return false;
	}

	console.log(result);
});
```

Yields: 

```javascript
{ element:
   { element_type: [ 'BASIC_CHECKBOX' ],
     element_call: [ '' ],
     element_content: [ '1' ] } }
```

**Comment by tflanagan** [comment]
Also, look at your error.

Is it REALLY coming from xml2js?

/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/__node_modules/mssql/node_modules/tedious/node_modules/babel-runtime/regenerator/runtime.js:493__

**Comment by maketroli** [comment]
@tflanagan this is the full error

```
/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/node_modules/babel-runtime/regenerator/runtime.js:493
        throw exception;
              ^
TypeError: Cannot read property 'toString' of null
    at Parser.exports.Parser.Parser.parseString (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/xml2js/lib/xml2js.js:466:16)
    at Parser.parseString (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/xml2js/lib/xml2js.js:6:59)
    at exports.parseString (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/xml2js/lib/xml2js.js:510:19)
    at /home/mretana/Documents/Projects/capilleiraclickandgamblebackend/api/services/ReportService.js:139:9
    at arrayMap (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/lodash/index.js:6710:14)
    at /home/mretana/Documents/Projects/capilleiraclickandgamblebackend/api/services/ReportService.js:134:16
    at arrayMap (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/lodash/index.js:6710:14)
    at toXml (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/api/services/ReportService.js:133:7)
    at /home/mretana/Documents/Projects/capilleiraclickandgamblebackend/api/services/ReportService.js:166:11
    at /home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/lib/main.js:1599:20
    at Request.userCallback (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/lib/tedious.js:990:59)
    at Request.callback (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/lib/request.js:39:27)
    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/lib/connection.js:311:29)
    at Connection.dispatchEvent (/home/mretana/Documents/Projects/capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/lib/connection.js:781:59)
```

**Comment by tflanagan** [comment]
So the error is coming from xml2js, but I can't reproduce it, as you can see in my comment above.

Can you describe the version of xml2js you are using, version of nodejs, and a slimmed down code snippet that allows someone to reproduce this.

**Comment by maketroli** [comment]
is there something wrong if I try to parse 3 different things in the same function, like this

```javascript
toXml = function(dataset) {
    return new Promise(function(fullfill, reject) {
      var cancel, view, fillOpen;
      _.map(dataset, function(items) {
        return _.map(items, function(item) {
          cancel = item.XX_CANCEL;
          view = item.XX_VIEW;
          fillOpen = item['XX_FILL OPEN'];

          parseString(cancel, function(err, res) {
            if (err) {reject(err);}
            cancel = JSON.stringify(res);
          });
          parseString(view, function(err, res) {
            if (err) {reject(err);}
            view = JSON.stringify(res);
          });
          parseString(fillOpen, function(err, res) {
            if (err) {reject(err);}
            fillOpen = JSON.stringify(res);
          });
          // console.log('fillOpen>>>', cancel);
        });
      });
    });
```

**Comment by tflanagan** [comment]
That is perfectly legal. 

Can you tell me what exactly line 493 is in your code?

./capilleiraclickandgamblebackend/node_modules/mssql/node_modules/tedious/node_modules/babel-runtime/regenerator/runtime.js:493

I still think this issue isn't with xml2js. Can you ```console.log()``` the ```res``` argument in the ```parseString``` argument?

**Comment by krusk** [comment]
I am having the same issue, and its with the basic call from the example on the project homepage as follows:

    var fs = require('fs');
    xml2js = require('xml2js');

    var parser = new xml2js.Parser();
    fs.readFile('http://mywebservice.net/info.xml', function (err, data) {
        parser.parseString(data, function (err, result) {
            console.dir(result);
            console.log('Done');
            res.send(result);
        });
    });

**Comment by Leonidas-from-XIV** [comment]
> its with the basic call from the example on the project homepage

I can't see where this would be on the homepage
```javascript
fs.readFile('http://mywebservice.net/info.xml', function (err, data) {
```

Problem is, you don't have such a file on your hard drive, so the data you are passing into `xml2js` is invalid. You probably want to use an HTTP client to read from that URL and then pass the data to `xml2js` instead.

**Comment by tflanagan** [comment]
I've submitted a PR, #244, that fixes catching this error

**Comment by krusk** [comment]
Thank you both, and my apologies for miscoding as I wrongly thought fs could interpret it from my Webservice. Would it be worthwhile to show an example of calling from a web service on the homepage? Do you have any preferences.

**Comment by krusk** [comment]
@Leonidas-from-XIV and @tflanagan, I have the following which returns the XML properly but passing this into the parser creates the same toString error:

    request('http://mywebservice.net/Info.xml', function (error, response, body) {
        if (!error && response.statusCode == 200) {
            console.log(body) // data
            var parser = new xml2js.Parser();
            fs.readFile(body, function (err, data) {
                parser.parseString(data, function (err, result) {
                    console.dir(result);
                    console.log('Done');
                    res.send(result);
                });
            });
        }
    })

**Comment by Leonidas-from-XIV** [comment]
@krusk Now you are trying to open a file that has the HTTP response content as a file name. You shouldn't use `fs.readFile`, instead you can feed the data directly to the parser.

**Comment by krusk** [comment]
Perfect. Works for me. Thank you for taking time to clear my head while I have been heads down in the "fog of code".
