### ISSUE TITLE
Preserving HTML elements

### ISSUE THREAD

**Issue by susnick** [Leonidas-from-XIV/node-xml2js#242]
I have one field in an xml document that contains HTML.

```
<CustomInstructions><b>This is really important -</b>  Complete legal description.<br /> <br /> Copies must be provided.<br /> <br /> Certificate of title must accompany the search</CustomInstructions> 
```

Can this preserved?

**Comment by Leonidas-from-XIV** [comment]
Is it XHTML or is it HTML?

**Comment by susnick** [comment]
HTML

**Comment by Leonidas-from-XIV** [comment]
I can't give any guarantees for HTML.

**Comment by tflanagan** [comment]
Can you include the entire XML document @susnick? Or atleast the surrounding nodes?

**Comment by susnick** [comment]
<VendorService>
								<ServiceId>6615159</ServiceId> 
								<ServiceCode>1OWNER</ServiceCode> 
								<CustomInstructions><b>This is really important -</b>  Complete legal description.<br /> <br /> Copies must be provided.<br /> <br /> Certificate of title must accompany the search</CustomInstructions> 
							</VendorService>

**Comment by tflanagan** [comment]
Do you have access to generating the XML?

If you do, wrap the ```CustomInstructions``` with ```<![CDATA[ ... ]]>```

That will "fix" the issue

**Comment by susnick** [comment]
Unfortunately I dont have access. Thanks anyways
