### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by tflanagan** [Leonidas-from-XIV/node-xml2js#247]
Hey @Leonidas-from-XIV,

Thank you for adding me to the Contributors object, I appreciate it!

Could you amend it from:
```Tristian Flanagan (https://github.com/tflanagan)```
to
```Tristian Flanagan <tflanagan@datacollaborative.com> (https://github.com/tflanagan)```.

Thanks!

**Comment by Leonidas-from-XIV** [comment]
Sure thing!

**Comment by tflanagan** [comment]
Thanks! :)
