### ISSUE TITLE
Specify a max depth?

### ISSUE THREAD

**Issue by Krisa** [Leonidas-from-XIV/node-xml2js#250]
Would it be possible to specify a maximum depth for the analysis of the XML? In my case, I need to analyse my XMLs till a depth of 2, and maybe having such an option could speed up the process? The value of the maximum node could be simply a string (non parsed xml).

**Comment by Leonidas-from-XIV** [comment]
I don't think that's possible, since the SAX parser processes the XML sequentially from first to last byte, without caring about the depth of the document. And when the XML parser is processing the whole file anyway, it wouldn't save much processing time if at all.
