### ISSUE TITLE
xml2js.parseString vs xml2js.parser.parseString

### ISSUE THREAD

**Issue by chacliff** [Leonidas-from-XIV/node-xml2js#253]
are the tagNameProcessors meant to be broken in the parser. i tried to use the parser specifically for parsing the string and removing a namespace on the xml and it broke hard. But when an associate of mine just did xml2js.parsestring it works fine. 
I'm reporting this as a bug since they don't seem to have the same functionality but they are named equivalently and documented as the same functions.

**Comment by Leonidas-from-XIV** [comment]
> are the tagNameProcessors meant to be broken in the parser

No, that would make no sense.

> I'm reporting this as a bug since they don't seem to have the same functionality but they are named equivalently and documented as the same functions.

They are not the same function. `xml2js` takes an optional `options` object for configuration, whereas `parseString` on a `Parser` instance does not, since the options are passed when creating an instance of the `Parser`.

Can you post a short example that works and one that doesn't?

**Comment by chacliff** [comment]
this works
<code> 
converter = require('xml2js'), 
 processors = require('xml2js/lib/processors'),
converter.parseString(response, {tagNameProcessors: [processors.stripPrefix]},function(err, result){
}) </code> 

This does not 
<code> 
converter = require('xml2js'), 
 processors = require('xml2js/lib/processors'),
parser = new converter.Parser(); 
parser.parseString(response, {tagNameProcessors: [processors.stripPrefix]},function(err, result){
}) </code>

**Comment by Leonidas-from-XIV** [comment]
Yes, this is because the `parseString` function supports up to 3 arguments: the data, options and the callback, whereas the `Parser.parseString` method only supports data and callback, the options have to be passed when creating a new instance of `Parser`.
