### ISSUE TITLE
Error: Text data outside of root node.

### ISSUE THREAD

**Issue by cubesapp** [Leonidas-from-XIV/node-xml2js#255]
I am getting an exception thrown with the latest release v0.4.15.  Obviously the xml being passed is badly formed.  To my understanding this was fixed in #118

var parser = new xml2js.Parser();

parser.parseString(data,function(err, result) {
   // do something;
});

**Comment by tflanagan** [comment]
Can you provide a sample snippet that repos this issue?

**Comment by compkidchris** [comment]
Also having this issue. I have some malformed XML coming in via a stream, and this exception is thrown every so often. Is there anyway to handle the error rather than allowing it to crash my app. The relevant exception returns the following message:

When exiting:
Error: Text data outside of root node.
Line: 0
Column: 40
Char: 1

err passed in the callback
Error: Parse Error

Was also under the impression this was previously solved.

**Comment by tflanagan** [comment]
@compkidchris and @cubesapp, we need sample code to replicate the issue

**Comment by compkidchris** [comment]
A more verbose error would be:

Offending XML:
<trade><cvol>9950902</cvol><datetime>2015-11-16T12:54:02-05:00</datetime><exch>NASDAQ Intermarket</exch><last>6.1
Purported Error:
[Error: Unclosed root tag
Line: 0
Column: 113
Char: ]
Offending XML:
</last><symbol>CHK</symbol><tcond>57,16</tcond><timestamp>1447696442</timestamp><vl>100</vl><vwap>6.083479</vwap></trade>
Purported Error:
[Error: Unmatched closing tag: last
Line: 0
Column: 7
Char: >]
Final Error:
Error: Text data outside of root node.
Line: 0
Column: 35
Char: 5
Error: Parse Error

The XML here is split across multiple calls to the parser, each snippet following "Offending XML: " is what is passed to the parser, Purported Error is the err from the parseString callback. The Final Error is the error/exception that ends my app. Let me know if this is helpful, I can provide some simple code which exemplifies this issue if need be.

**Comment by tflanagan** [comment]
@compkidchris, am I understanding this correctly?

You are streaming an XML document and are trying to parse it with each chunk you receive?

If that assumption is correct then change your workflow to parse after all chunks are gathered. `parseString` can't handle streams, due to underlying dep limitations.

**Comment by compkidchris** [comment]
Will do, not sure if @cubesapp has another issue entirely though.

**Comment by cubesapp** [comment]
I haven't been able to reproduce the issue lately. So I don't have the xml and code snippet yet!  We have made code changes on our end recently to ensure that MOST XML documents being passed to parseString are valid.

Sending partial XML documents via stream to parseString seems to be the issue (which we were doing).  Ideally, if parseString returns an error instead of throwing an exception would be best; in order to handle this issue.

**Comment by tflanagan** [comment]
@cubesapp I just want to reiterate that `parseString` cannot handle streams. You __must__ pass in the entire XML document for a successful parse.

>> Ideally, if parseString returns an error instead of throwing an exception would be best; in order to handle this issue.

I don't understand what you mean by returns an error. `parseString` is synchronous, so to catch any errors, as with any other nodejs sync function, you must wrap it in a `try/catch`

**Comment by jcsahnwaldt** [comment]
@cubesapp 
> Would I wrap it in an a try/catch? If this is the case, thanks and I am good to go with this.

That's correct. See https://github.com/Leonidas-from-XIV/node-xml2js/issues/67 and https://github.com/Leonidas-from-XIV/node-xml2js/issues/408 for details.

**Comment by jcsahnwaldt** [comment]
I guess this can be closed...
