### ISSUE TITLE
builder: indent: default indent

### ISSUE THREAD

**Issue by Krisa** [Leonidas-from-XIV/node-xml2js#259]
would it be possible to add an option for the builder to add eventually a default indent for the block?

use case: I'm building relatively complex documents and I need to build "sub" xml part of the document so that currently, it looks like the components are belonging to the "root", while they don't. This option could be part of the "renderOpts".

**Comment by Leonidas-from-XIV** [comment]
To be honest, I think this is out of scope for xml2js. You can easily plug in any XML prettyprinter and customize it to your needs, no need to pack in such a feature.

**Comment by Krisa** [comment]
Actually, my problem got just solved magically because... the feature already exists... https://github.com/oozcitak/xmlbuilder-js/wiki. I'm surprised of your comment, but it seems just like a hidden feature :-)
