### ISSUE TITLE
Change xmlbuilder required version to stop warnings

### ISSUE THREAD

**Issue by SamuelMarks** [Leonidas-from-XIV/node-xml2js#264]
I am installing some package, which depends on another (and another) and eventually `xml2js`. `xml2js` depends on a bunch of packages, including `"xmlbuilder": ">=2.4.6"`.

The WARNing I keep getting is:
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

One way of stopping this warning is to use the latest version of `xmlbuilder-js` (see its [package.json](https://github.com/oozcitak/xmlbuilder-js/blob/6c85637319f17dca053992d1a53572036d57c2dc/package.json)), which depends on: `"lodash": "^3.5.0"`.

**Comment by Leonidas-from-XIV** [comment]
Thanks for letting me know!

**Comment by SamuelMarks** [comment]
:)
