### ISSUE TITLE
Allow to specify the #name key

### ISSUE THREAD

**Issue by felixfbecker** [Leonidas-from-XIV/node-xml2js#270]
I would like to have my XML object structured like a Node in the DOM API: https://developer.mozilla.org/de/docs/Web/API/Node/nodeName
 - child elements under `childNodes` key as an array. I set `{childkey: 'childNodes', explicitChildren: true, preserveChildrenOrder: true}`
 - name of the node under `nodeName` key. How can I set this? It is always under `#name`
 - attributes as `attributes` key. I set `attrkey: 'attributes'`
 - text content as `nodeValue`

**Comment by hassanf1** [comment]
Do you mean the target here which is JS, or the source (XML).. I have done something on XML to JS parsing using DOM. Please explain, I would see if I can help.

**Comment by felixfbecker** [comment]
I wanted to get objects out of xml2js that are compatible with the DOM specification. But I just switched over to [xmldom](https://www.npmjs.com/package/xmldom), which is following the DOM specification exactly.
