### ISSUE TITLE
JSON.parse error

### ISSUE THREAD

**Issue by hassanf1** [Leonidas-from-XIV/node-xml2js#275]
Hi, 

While I am trying to parse an XML into json object I am getting 'Unexpected token' error.

Source XML (PO.xml):
-----------------
<PurchaseOrder><PONumber>54300045</PONumber><CustomerNumber>21210001</CustomerNumber><Priority>High</Priority><POLines><POLinesSummary>This section is for POLin…</POLinesSummary><POLinesType>Standard</POLinesType><POLine><LineNo>10</LineNo><ProductId>XGF4537ez</ProductId><Quantity>100</Quantity><ShipDate>2016-04-12</ShipDate></POLine><POLine><LineNo>20</LineNo><ProductId>ZZQR 785ff</ProductId><Quantity>50</Quantity><ShipDate>2016-03-28</ShipDate><SubLineItem><SubLineNo>21</SubLineNo><SubLineQty>12</SubLineQty><Weigth>10</Weigth></SubLineItem><SubLineItem><SubLineNo>22</SubLineNo><SubLineQty>20</SubLineQty><Weigth>17</Weigth></SubLineItem></POLine><POLinesType1>Standard</POLinesType1></POLines></PurchaseOrder>

My JS (node) code:
--------------------------
let parseString = require('xml2js').parseString;
let fs = require('fs');
let util = require('util');

let xmlData = fs.readFileSync('PO.xml', 'utf-8');
parseString(xmlData, {trim: true}, (err, result) => {
	console.log(util.inspect(result, false, null));    // OK. Prints json text
	console.log('parsing json text to js object..');
	let dObj = JSON.parse(result);	// here I am getting error.

Error:
--------
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token o
    at Object.parse (native)
    at /Users/../test_xml2js.js:12:18
    at Parser.<anonymous> (/Users/../node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/Users/../node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/Users/../node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/../node_modules/sax/lib/sax.js:644:5)
    at closeTag (/Users/../node_modules/sax/lib/sax.js:903:7)
    at Object.write (/Users/../node_modules/sax/lib/sax.js:1436:13)

Is there a bug in the parser or please suggest if I need to do something different ?

Rg,
-Farrukh

**Comment by hassanf1** [comment]
XML enclosed in cdata:

<![CDATA[
<PurchaseOrder><PONumber>54300045</PONumber><CustomerNumber>21210001</CustomerNumber><Priority>High</Priority><POLines><POLinesSummary>This section is for POLin…</POLinesSummary><POLinesType>Standard</POLinesType><POLine><LineNo>10</LineNo><ProductId>XGF4537ez</ProductId><Quantity>100</Quantity><ShipDate>2016-04-12</ShipDate></POLine><POLine><LineNo>20</LineNo><ProductId>ZZQR 785ff</ProductId><Quantity>50</Quantity><ShipDate>2016-03-28</ShipDate><SubLineItem><SubLineNo>21</SubLineNo><SubLineQty>12</SubLineQty><Weigth>10</Weigth></SubLineItem><SubLineItem><SubLineNo>22</SubLineNo><SubLineQty>20</SubLineQty><Weigth>17</Weigth></SubLineItem></POLine><POLinesType1>Standard</POLinesType1></POLines></PurchaseOrder>
]]>

**Comment by hassanf1** [comment]
again.. attaching as file.
[PO.xml.txt](https://github.com/Leonidas-from-XIV/node-xml2js/files/100265/PO.xml.txt)

**Comment by tflanagan** [comment]
I think you're confused as to the variable type of `results` from `parseString`.

You don't need to parse the results, it is already an object.

Try this in your console:

```
$ node
> JSON.parse({});
SyntaxError: Unexpected token o
    at Object.parse (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
```

**Comment by hassanf1** [comment]
Thanks tflanagan.. my bad.
