### ISSUE TITLE
Add support for xpath

### ISSUE THREAD

**Issue by ayeressian** [Leonidas-from-XIV/node-xml2js#279]
Xpath can be used to get or parse a part of xml document.

**Comment by Leonidas-from-XIV** [comment]
XPath is just for accessing elements in a document, where would xml2js support this? In the retrieval of elements from the parsed object?

Maybe you want [JSONPath](http://goessner.net/articles/JsonPath/)? Then you can traverse the resulting plain JS object with a query language that is kinda similar to XPath.

**Comment by ayeressian** [comment]
Hmm... I was thinking about performance optimisation. But maybe the cost of executing xpath is roughly the same as parsing the document.

**Comment by Leonidas-from-XIV** [comment]
For XPath traversal you already need the parsed document.

**Comment by ayeressian** [comment]
Ok sounds reasonable. Thanks
