### ISSUE TITLE
parse error [Error: Attribute without value

### ISSUE THREAD

**Issue by dcsan** [Leonidas-from-XIV/node-xml2js#281]
I have some XML which has some odd data in it, is there a way to ignore this?

```xml
<tw-storydata name="flow" startnode="1" options="" hidden>...

```
the last attribute is choking the parser:

    hidden>

This is generated by another app so I would prefer to just ignore empty attributes

**Comment by tflanagan** [comment]
@dcsan, what's the error?

**Comment by Leonidas-from-XIV** [comment]
That's not XML, that's why the parser can't parse it. You could try preprocessing it with something like HTML Tidy to convert it to valid XML first.

**Comment by dcsan** [comment]
if i remove the `hidden` emtpy tag, it will parse. I realize it's not fully legal XML, but i was asking if there were any params to make the parser be more lenient, or if i have to preprocess the XML.

**Comment by Leonidas-from-XIV** [comment]
No, there aren't. It relies on the XML being well-formed.

**Comment by sahin52** [comment]
Is this updated? Is there another xml parser that can do this?
