### ISSUE TITLE
buildObject() is not working in latest version of xmlbuilder

### ISSUE THREAD

**Issue by bhalajin** [Leonidas-from-XIV/node-xml2js#288]
xmlbuilder has been updated to v8.0.0 last week. The buildObject() in the xml2js.Builder object is not compatible with this version of xmlbuilder.

**Comment by Leonidas-from-XIV** [comment]
I've tried it with 7.0.0 and tests passed. Can't try it with 8.x, since it drops compatibility with older nodejs.

**Comment by bhalajin** [comment]
Is it possible to fix the version in the package.json because it always fetches the latest version of xmlbuilder which is v8.0.0?

**Comment by Leonidas-from-XIV** [comment]
The version is fixed: `^4.1.0` which is supposed to only install versions `4.1.x`… (on my system it somehow installs `4.2.1` but that works as well).

**Comment by bhalajin** [comment]
Thanks for the reply. I guess I have misunderstood the caret, but got it cleared now
It is installing 4.2.1 only...
