### ISSUE TITLE
xml2js not work with webpack due to circular require

### ISSUE THREAD

**Issue by ComLock** [Leonidas-from-XIV/node-xml2js#292]
```
ERROR in ./~/xml2js/lib/bom.js
Module not found: Error: a dependency to an entry point is not allowed
 @ ./~/xml2js/lib/bom.js 6:11-35
```

xml2js.js requires bom.js
https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L15

bom.js requires xml2js.js
https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/bom.js#L4-L6

"Like a circle!"

Can't those lines in bom.js simply be deleted? I can't see that they are used?

Or even better why not use:
https://www.npmjs.com/package/strip-bom

**Comment by Leonidas-from-XIV** [comment]
Thanks for the report, as you saw I've pushed a fix.

> Can't those lines in bom.js simply be deleted? I can't see that they are used?

Yes. I don't know why they were there originally.

> Or even better why not use: https://www.npmjs.com/package/strip-bom

I don't want to include ridiculous dependencies like left-pad.
