### ISSUE TITLE
cannot parse '&'

### ISSUE THREAD

**Issue by huquduy** [Leonidas-from-XIV/node-xml2js#296]
Hi Leo, I have a problem with this xml 
 <result>http://sport2.eg.1sgames.com/public/validate.aspx?us=***&k=***&lang=EN-US&r=***</result>
I try debuged, It working without '&' 
How can I resolve it?
Thanks!

**Comment by Leonidas-from-XIV** [comment]
When I check the URL, I'm not getting out any valid XML, so I am having trouble to help you to debug this issue.

**Comment by huquduy** [comment]
yep, I mean format like that : "<data>domain/api&param</data>"
seem that Invalid XML with characters '&'

**Comment by Leonidas-from-XIV** [comment]
Sorry I don't follow. Can you post an example of XML that xml2js can't parse?

**Comment by huquduy** [comment]
ok, I resolve this issue with `xmlstr = xmlstr.replace(/&/g, "&amp;");`
Thanks Leo
your repo so great :+1:
