### ISSUE TITLE
blast xml stops parsing

### ISSUE THREAD

**Issue by enuggetry** [Leonidas-from-XIV/node-xml2js#306]
I seem to have a problem parsing this XML, where the objects after Iteration are undefined.

```
var parser = new xml2js.Parser();
fs.readFile(blastxmlfile, function(err, data) {
    parser.parseString(data, function (err, obj) {
      var hits = obj.BlastOutput.BlastOutput_iterations.Iteration.Iteration_hits.Hit;

```
[Blast230.xml.txt](https://github.com/Leonidas-from-XIV/node-xml2js/files/305699/Blast230.xml.txt)

Note: these other parsers work fine
http://www.utilities-online.info/xmltojson/#.V1iYr5ErJWM
and npm xmljson

**Comment by Leonidas-from-XIV** [comment]
Can you provide a runnable example that exhibits that problem?

**Comment by enuggetry** [comment]
Thanks.
Figured it out.  It seems xml2js likes to put things into arrays, more so than the other parsers.
