### ISSUE TITLE
Migration to new versions of `xmlbuilder-js`

### ISSUE THREAD

**Issue by mrmlnc** [Leonidas-from-XIV/node-xml2js#318]
Hello,

I think it makes sense to update the `xmlbuilder-js` dependency to the new version. This will reduce your package up to 180 kilobytes instead of 1 megabyte.

**Comment by Leonidas-from-XIV** [comment]
Why is the new version so dramatically smaller?

But yes, if that's the case I think it is a good idea. I just hope that the changes required aren't too big.

**Comment by mrmlnc** [comment]
@Leonidas-from-XIV, they have removed Lodash from dependencies (https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md#820---2016-04-01).

I ran tests from this repository and they passed.

**Comment by mrmlnc** [comment]
@Leonidas-from-XIV, thanks!
