### ISSUE TITLE
Node inspector issue

### ISSUE THREAD

**Issue by lucianoybanez** [Leonidas-from-XIV/node-xml2js#322]
I'm using node inspector for debug, when I have an mssql connection to Microsoft SQL database with new version xml2js 0.4.16 thrown an error with Time out period.
Thanks

**Comment by Leonidas-from-XIV** [comment]
I have no idea. Without any code to reproduce it's going to be impossible to say anything.

**Comment by lucianoybanez** [comment]
Ok, you just can make a connection using mssql to connect to DB and add requiere to  xml2js library, just that. Remember  xml2js 0.4.16 or up.
Thanks

**Comment by Leonidas-from-XIV** [comment]
I don't have access to mssql.

**Comment by lucianoybanez** [comment]
OK, mssql is a library for connect with SQL. var sql = require('mssql');
Thanks

**Comment by Leonidas-from-XIV** [comment]
Yes, but for this I need to have access to a mssql server, which I don't.

Also, I don't think this has anything to do with MSSQL.

**Comment by lucianoybanez** [comment]
OK, It seems to be strange, when up debug with line: node --debug app.js is to slow. But when up with two lines off course different console: node-inspector --save-live-edit and node --debug app.js, works fine and it is to faster.
Thanks anyway.
