### ISSUE TITLE
Motivation for the output JSON structure?

### ISSUE THREAD

**Issue by cmmartin** [Leonidas-from-XIV/node-xml2js#323]
I am curious as to the motivation for the structure of the JSON output? It seems to me that the JSON structure returned is far from ideal...

Why not something simple like...

```
<div id="myDiv">
  ...
</div>
```

would become

```javascript
{
  tag: 'div',
  attributes: { 
    id: 'myDiv'
  },
  children: [ ... ]
}
```

These data types match their XML counterparts. Tags are just strings. Attributes are non-ordered, key-value pairs. Children are ordered and have no keys. This makes it simple to recursively crawl the tree as well. 

I believe this structure would remove the need for any special options to change the output format whatsoever.

Given the popularity of this repo, I feel like I must be missing something? I'm considering writing a library to convert XML to this format, but wondering if anyone is aware of cases that I won't be able to handle?

**Comment by cmmartin** [comment]
So I think maybe I answered my own question. I'd imagine this structure was chosen in order to do quick look ups. For example...

```
<div><navbar></navbar></div>
```

Can be accessed with...
```
result.div.$$.navbar
```

This was more desirable before ES6 with native `Array.prototype.find` and arrow functions. The same lookup with the output format I mentioned above could now be done relatively painlessly with...

```
result.children.find(child => child.tag === 'navbar')
```

This would have been an imperative mess without `.find` and couldn't be a one liner without arrow functions. It's also likely less performant in large structures because it has to at least partially iterate children

**Comment by Leonidas-from-XIV** [comment]
@cmmartin Yes, you're exactly right. That's also why the default "special" keys are `$` and `_`: these are valid characters for JS variables to start and do not require `["key"]` notation for attribute access.

There is also the issue of explicit arrays. Overall, I believe that this a bad idea even if they are less verbose, that's why there are options to control whether children are in lists or unpacked.
