### ISSUE TITLE
cannot parse

### ISSUE THREAD

**Issue by Adam-Burke** [Leonidas-from-XIV/node-xml2js#324]
I have the following code. I have tried the parser with the copy and pasted string from the file and it works fine so it isn't a structural issue with the svg. 

``` javascript
watcher
  .on('add', function(path, test) { 
    fs.readFile(path, 'utf8', function(error, data) {
        // var data = data.slice(2, data.length).replace(/\s+/g, '');
               // var data = data.replace("\ufeff", "");
        parseString(data, function(error, json){
            console.log(error);
            console.log(json);
        })
    })
  })
```

Unchanged I get the following error: 

**[Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �]**

I then modified the string to ignore the first two characters and I get the following issue.

**[Error: Unencoded <
Line: 0
Column: 2
Char: ]**

I similarly tried this solution from here http://www.multiasking.com/blog/xml2js-sax-js-non-whitespace-before-first-tag/ and got the following error.

**[Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �]**

**Comment by Adam-Burke** [comment]
Arghh. Sorry I'll look into formatting that code better when I return.

**Comment by Leonidas-from-XIV** [comment]
The issue the blog post mentions is already fixed (also, solves it better as it does not delete all occurences of `\uFEFF`) in xml2js since a long time, so no need to strip off characters from the input.

**Comment by cassavite** [comment]
Hi Leonidas, Please kindly advise on the exact solution. Do i need to upgrade xml2js to the latest version?

**Comment by Leonidas-from-XIV** [comment]
This was fixed a couple of versions ago, so unless you're using an ancient version, you should be fine.

**Comment by cassavite** [comment]
Hi Marek,
Thanks for the response. It is working now perfectly. I was reading the
output incorrectly.

Best Regards,

Aluko

**Comment by MegaArman** [comment]
This issue doesn't seem fixed to me. I have exactly the same issue with 0.4.17.  Ex: 
http://openmusicscore.org/media/com_form2content/documents/c1/a90/f7/Beethoven-Symphony%20No.%201%20(1799).zip

**Comment by Leonidas-from-XIV** [comment]
Oh, so this is not about BOM but rather DOS line endings. Hmm, yeah, that needs to be handled.

**Comment by xiaoxinshiwo** [comment]
> This issue doesn't seem fixed to me. I have exactly the same issue with 0.4.17. None of the files here work: http://openmusicscore.org/media/com_form2content/documents/c1/a90/f7/Beethoven-Symphony%20No.%201%20(1799).zip
> 
> I highly recommend http://www.linuxcommand.org/man%5Fpages/dos2unix1.html dos2unix is a quick fix solution for the time being

Thanks, works for me.
