### ISSUE TITLE
Mandatory root tag

### ISSUE THREAD

**Issue by Ali-Amechghal** [Leonidas-from-XIV/node-xml2js#330]
When i use a file with content like bellow it will generate only the first part

``` XML
<!-- first -->
<Address>
    <street>Paradise street</street>
    <city>Heaven</city>
</Address>
<!-- second-->
<Address>
    <street>Hell street</street>
    <city>Hell</city>
</Address>>
```

in this case it will only convert the first address tag.

result : 

``` JSON
{
  "Address": {
    "street": [
      "Paradise street"
    ],
    "city": [
      "Heaven"
    ]
  }
}
```

when i add a global root tag  like bellow it parse the whole content as expected:

``` XML
<data>
    <!-- first -->
    <Address>
        <street>Paradise street</street>
        <city>Heaven</city>
    </Address>
    <!-- second-->
    <Address>
        <street>Hell street</street>
        <city>Hell</city>
    </Address>
</data>
```

result : 

``` JSON
{
  "data": {
    "Address": [
      {
        "street": [
          "Paradise street"
        ],
        "city": [
          "Heaven"
        ]
      },
      {
        "street": [
          "Hell street"
        ],
        "city": [
          "Hell"
        ]
      }
    ]
  }
}

```

**Comment by solowt** [comment]
XML must have a single root node.  If it doesn't, then you can't sensibly use it to represent a tree.

**Comment by Leonidas-from-XIV** [comment]
Yes, that's exactly the reason why it only parses the first root node.

**Comment by RAPIDFACTURE** [comment]
I had just the same issue. Having a root element seems reasonable to me. I suggest adding this to the docs:

"A root element is mandatory; it ensures complete data and you can throw an error otherwise."
