### ISSUE TITLE
Problem with parse ending "s" as array

### ISSUE THREAD

**Issue by gitrus** [Leonidas-from-XIV/node-xml2js#342]
As i understand [parser.cofee:174](https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/src/parser.coffee) is a case with processing tag-props ending with "s" but i have some xml with  ```<SptOptions>104</SptOptions> ``` which parse as ```SptOptions: [null]```
Can you explain me why u doesn't handle this case and what can i do with this behavior?

**Comment by Leonidas-from-XIV** [comment]
It is not processing tag-props ending with `s` any different than others.

**Comment by gitrus** [comment]
It's not explain behavior of parser.

> <SptOptions>104</SptOptions> which parse as SptOptions: [null]

**Comment by Leonidas-from-XIV** [comment]
For me this XML parses as

```json
{ SptOptions: '104' }
```
