### ISSUE TITLE
Non-whitespace before first tag in xmls2js

### ISSUE THREAD

**Issue by kkp2004** [Leonidas-from-XIV/node-xml2js#345]
Below code i am running and trying to parse XML response through xmls2js, 

soapClient.call({
	'method':'findAll',
	'params' : {
          'maxResults'  : 100,
          'orderDirection' : 0,
          'orderField' : 'creationdate',
           'startIndex' :1
      }
	  }
)
    .then(function(res) {
    	console.log(res.response);
            res.data        // response data as array
            var data=res.response    // full response data (including xml)
            res.header      // response header

            parseString(data, function(err, result){
                if(err) console.log(err);
                console.log(result); 
            });
        },
        function(err) {
            console.log(err);
        }
    );  
While running the code getting below error.

Error: Non-whitespace before first tag.

**Comment by Leonidas-from-XIV** [comment]
How does the XML you pass in look like?

**Comment by fxlemire** [comment]
[This blog](http://www.multiasking.com/blog/xml2js-sax-js-non-whitespace-before-first-tag/) solved it for me.

**Comment by Leonidas-from-XIV** [comment]
This should work out of the box, since xml2js has now code to remove the byte order mark before parsing.

**Comment by lucifer-AM** [comment]
@fxlemire I am facing the same issue and the blog link is not working.

Please provide a solution. Thank you!.

**Comment by fxlemire** [comment]
@lucifer-AM To fix the issue:

`var cleanedString = origString.replace("\ufeff", "");`

**Comment by lafiza** [comment]
Having same error.

and var cleanedString = origString.replace("\ufeff", ""); didnt work for me.

attached sample xml

[xml.txt](https://github.com/Leonidas-from-XIV/node-xml2js/files/1152851/xml.txt)

**Comment by lucifer-AM** [comment]
@fxlemire I have a feed Reader that I created for RDF, ATOM as well as RSS. It works fine for all three but for some feeds it give this error.
Error: Non-whitespace before first tag.
Currently I think it is related to the HTTP response that I am getting after I hit the feed URL. As the response is garbled I can't give it to the xml2js.
Currently I am avoiding the erroneous feed urls.
Thanks anyways.

**Comment by marcelolfilho** [comment]
Any fix?

**Comment by justintemps** [comment]
This probably isn't the library's fault. Make sure you're not trying to parse the entire result object of some ajax request and just the XML data.

**Comment by Desireedaccache** [comment]
I have the same issue. Any solutions?

**Comment by gribeiro8** [comment]
Try this...
fs = require('fs');
   var parseString = require('xml2js').parseString;

   fs.readFile('../storage/epg/epg.xml', function(err, data) {
      var data = data.toString().replace("\ufeff", "");
      parseString(data, function (err, result) {
         console.dir(result);
      });
   });

**Comment by hi2meuk** [comment]
XML files are utf8 and when stored as a file should have a binary header ("\ufeff").  The previous comment solve this by removing it before passing it.  An alternative is to use fs.readfile which will deal with the header.

'''
fs.readFile('../simple test.xml', function(err, data) {
    var doc = new xmldoc.XmlDocument(data);
'''

**Comment by jenweber** [comment]
Thanks everyone for sharing your solutions and to the authors of this library for creating it! This thread was helpful to me.

In case it helps someone else, here's a full example, going from xml file with binary headers to writing the results to a file.

```javascript
const fs = require('fs');
const util = require('util')
const parseString = require('xml2js').parseString;
const fileToParse = ('./my-file.xml')
const outputFilename=('output.json')

fs.readFile(fileToParse, function (err, data) {
    parseString(data, function (err, result) {
        console.dir(result);
        if (err) {
            console.log(err)
        }
       // do something with the JS object called result, or see below to save as JSON
        fs.writeFile('output.json', JSON.stringify(result), (writeErr) => {
            if (writeErr) throw writeErr;
            console.log('The file has been saved to ' + outputFilename);
        });
    });
});
```

If you try to write the JS object straight to a file, you get `[Object object]` in the file, so I converted to JSON.

**Comment by voe1999** [comment]
> I had the same issue, but then I realized I was trying to parse the entire response object of an AJAX request instead of just the response data.

fk me

**Comment by sratemo** [comment]
I used a try and catch block, worked perfectly for me.

**Comment by ericmadureira** [comment]
@justintemps, you just saved me, thank you so much!! haha

**Comment by maurocolella** [comment]
Try passing 
```
{
    preserveWhitespace: true
}
```

In `options` when instantiating the client.

**Comment by jason-warner** [comment]
This may be overkill or an obtuse approach but this did the trick for my https server receiving XML webhooks. 
This snippet depends on express and I'm using DOMParser from xmldom to clean the data before it is parsed.

```
app.post("/test", (req, res) => {
  let body = '';
  req.setEncoding('utf8');
  req.on("data", (chunk) => {
    body += chunk;
  });
  req.on('end', () => {
    const tempData = body.toString();
    try {
      const cleanData = new DOMParser().parseFromString(tempData, "text/xml");
      return parseString(cleanData, (err, result) => {
        if (err) {
          console.log(err)
          res.statusCode = 400;
          return res.end("Error 2: " + err)
        } else {
          console.log(result);
          res.statusCode = 200;
          return res.end("Success.");
        }
      });
    } catch (err) {
      console.log(err);
      res.statusCode = 400;
      return res.end("Error 1: " + err);
    }
  });
});
```
Console:

![image](https://user-images.githubusercontent.com/49247631/124180684-8bbdaf80-da82-11eb-853a-a63df151be7a.png)


Ngrok inspection: 

![image](https://user-images.githubusercontent.com/49247631/124180457-371a3480-da82-11eb-8875-08ac8d0f4981.png)

**Comment by gentildpinto** [comment]
> I had the same issue, but then I realized I was trying to parse the entire response object of an AJAX request instead of just the response data.

Same to me, I'm feeling very stupid right now hahahaha
Thanks.

**Comment by sh977218** [comment]
> [This blog](http://www.multiasking.com/blog/xml2js-sax-js-non-whitespace-before-first-tag/) solved it for me.

this blog no longer exists. Can someone post the solution.
