### ISSUE TITLE
manage array

### ISSUE THREAD

**Issue by BUONJG** [Leonidas-from-XIV/node-xml2js#346]
Hello,

I have an issue using the library when XML contains array.

When I parse:

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
  <id>1234</id>
  <lines>
    <id>1</id>
    <name>name</name>
  </lines>
  <lines>
    <id>2</id>
    <name>name2</name>
  </lines>
</root>
```

It returns as expected:
```
{
   "root": {
      "id": "1234",
      "lines": [
         {
            "id": "1",
            "name": "name"
         },
         {
            "id": "2",
            "name": "name2"
         }
      ]
   }
}
```

But when I try to parse:
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
  <id>1234</id>
  <lines>
    <id>1</id>
    <name>name</name>
  </lines>
</root>
```

I get:
```
{
   "root": {
      "id": "1234",
      "lines": {
         "id": "1",
         "name": "name"
      }
   }
}
```

But my code is still expecting to have lines as array.

Is there a way to have this behavior?

Regards,

**Comment by Leonidas-from-XIV** [comment]
Yes, the `explicitArray` option (it should be default but would break a lot of code, that's why it's not).

**Comment by BUONJG** [comment]
I tried explicitArray but it returns:
```
{
   "root": {
      "id": ["1234"],
      "lines": [{
         "id": "1",
         "name": "name"
      }]
   }
}
```

Then id is also an array, it's really not what I expect.

Is there a way to force the segment be parsed as array adding an attribute array=true for instance:
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
  <id>1234</id>
  <lines array=true>
    <id>1</id>
    <name>name</name>
  </lines>
</root>
```

**Comment by Leonidas-from-XIV** [comment]
It can't guess every possible usecase or dispatch on values of the tree.

**Comment by BigZolo** [comment]
+1 for this feature request: 
possible usecase:
``` xml
<p name="a">
  <w name="w1" />
  <w name="w2"/>
</p>
<p name="b">
  <w name="w3" />
</p>
```
this will be:
```javascript
{
  "p": [{
    "name": "a",
    "w": [{
      "name": "w1"
    }, {
      "name": "w2"
    }]
  }, {
    "name": "b",
    "w": {
      "name": "w3"
    }
  }]
}
```
which is not good because "w" once is an array, but next time is an object. When I process the array of "p"-s, always have to check that the "w" is array.

**Comment by Leonidas-from-XIV** [comment]
That's why `explicitArray` `true` is the setting that I recommend to people.
