### ISSUE TITLE
processor signature not working for me 

### ISSUE THREAD

**Issue by myfygx** [Leonidas-from-XIV/node-xml2js#356]
I wrote something like this: 

function parseNumberProcessor(value, key) {
    console.log("My NODE: "+ key + " My value: "+ value);
    let isNumberNode = true;
        if ('account' === key) {
            isNumberNode = false;
        }
    if ((!isNaN(value))&&(isNumberNode)) {
        value = value % 1 === 0 ? parseInt(value, 10) : parseFloat(value);
    }
    return value;
}

const xml = '<account><accountNumber>0012345</accountNumber><balance>123.45</balance></account>';
xml2js.parseString(xml, {
valueProcessors: [parseNumberProcessor]}, function(err, result) {
                console.log(result);
						}
);

And the console out put is: 
My NODE: undefined My value: 0012345
My NODE: undefined My value: 123.45
{ account: { accountNumber: [ 12345 ], balance: [ 123.45 ] } }

Seems valueProcessors could not accept the signature for value and key. But in the test, I see there is a similar test passed, not sure how could I handle that

**Comment by myfygx** [comment]
Seems xml is not displayed correctly, it's the same as in the test
<account><accountNumber>0012345</accountNumber><balance>123.45</balance></account>

**Comment by npopov-d3** [comment]
I am having same issue, trying to pass 
{
   attrValueProcessors: [myFunc]
}

where
function myFunc(val, key) {
console.log(key);
return val;
}

key is undefined..

**Comment by mrsum** [comment]
Same for me

**Comment by Leonidas-from-XIV** [comment]
Can you post a minimal, working example?

**Comment by npopov-d3** [comment]
Thank you,

var parseString = require('xml2js').parseString;
var xml = "<root attr='foo'>Hello xml2js!</root>";

function foo(val, name) {
   console.log("called with", val);
   console.log("but the name is", name);`
   if (name === 'attr') {
      console.log('eurika!');
   }
   return val;
}
parseString(xml, {
   attrValueProcessors: [foo]
}, function (err, result) {
   console.dir(result);
});

**produces:**
node try.js
called with foo
but the name is undefined
{ root: { _: 'Hello xml2js!', '$': { attr: 'foo' } } }

**environment**
node 6.9.2
package.json:
...
  "dependencies": {
    "xml2js": "^0.4.17"
  }

**Comment by felixbecker** [comment]
Any updates on this? I have the same issue. It seems like the key is not passed. 

According to the docs in readme this should work, but does not for me.
```
The attrValueProcessors and valueProcessors options accept an Array of functions with the following signature:

function (value, name) {
  //`name` will be the node name or attribute name
  //do something with `value`, (optionally) dependent on the node/attr name
  return value
}
```

**Comment by patrickclancy** [comment]
I'm having the same issue. Using this signature for the valueProcessors function, value has the correct value but name is always undefined.   
`
function (value, name) {
    return value
}
`
