### ISSUE TITLE
XSD support

### ISSUE THREAD

**Issue by skylize** [Leonidas-from-XIV/node-xml2js#361]
Thanks for the great work.

Would be nice to see this fork merged back into a project with active maintenance. He started with xml2js and added the feature of using XSD files for cleaner parsing.

[node-xml4js](https://github.com/peerlibrary/node-xml4js)

**Comment by Leonidas-from-XIV** [comment]
This does not look like a fork but rather a downstream project which adds support for XSD. That's very nice but I don't see the necessity to include this functionality which happily lives in its own project.

**Comment by skylize** [comment]
Hmm, looking closer that seems true. I withdraw. 😄
