### ISSUE TITLE
In case of error Attribute without value. The err will return null on second try (actually for each even try)

### ISSUE THREAD

**Issue by amotzte** [Leonidas-from-XIV/node-xml2js#365]
```javascript
const parseString = require('xml2js').Parser().parseString;
const invalidXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<PurchasableTitleRequest from test";
parseString(invalidXml, function (err, result) {
    console.dir(err.message); // This will work and print 'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
});
parseString(invalidXml, function (err, result) {
    console.dir(err); // Here err will be null (so if I tried to call message it would crash)
});
parseString(invalidXml, function (err, result) {
    console.dir(err.message); // This will work again
});
```

Expected output 
```
'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
```

Observed output
```
'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
null
'Attribute without value\nLine: 1\nColumn: 31\nChar: t'
```

**Comment by Leonidas-from-XIV** [comment]
That's because you are recycling the instance of the parser and after the first parsing it is in a messed up state.

Try with this code
```javascript
const parseString = require('xml2js').parseString;
```

This is documented in the [README](https://github.com/Leonidas-from-XIV/node-xml2js#parsing-multiple-files):

>     You can hope everything goes well anyway. This behaviour is not guaranteed work always, if ever. Use option #1 if possible. Thanks!

**Comment by Leonidas-from-XIV** [comment]
> Maybe it worth just throwing an exception if someone is trying to recycling the instance(?)

That's a good idea, the problem here is that it might suddenly trip up code that always used to work, kinda like yours, so that's an issue.

**Comment by amotzte** [comment]
Interesting... just by scanning some other projects, it seem highly common to defined it is global variable (like I did), and calling it on every http request. I guess it means that for the happy flow it safe to say it is working (or people would complain more often). I'm wondering what (if any) the performance cost of creating a new instance on each http request. I'll try to run siege and update with the results.
Thanks.
