### ISSUE TITLE
Issue with XML wit DTD

### ISSUE THREAD

**Issue by loretoparisi** [Leonidas-from-XIV/node-xml2js#366]
I have [this](https://gist.github.com/loretoparisi/2620b777562c2dfd50d6b618b5f20867) xml output from the `nvidia-smi -x -q` command
It seems to be a valid XML, but when I put it inside the parser as for the simplest example

```javascript
parseString(xmlString, function (err, result) {
    console.log( JSON.stringify(result,null,2) );
});
```

I get an `undefined` as output.

[Another](https://gist.github.com/loretoparisi/6e98a3afe62f5365145135cb60021b81) simple gpu output example (just one gpu) works fine instead. See [here](https://gist.github.com/loretoparisi/341355ff00f2d79c5a062acd1f6d5606) for the converted json.

Both XML declares a DTD: `<!DOCTYPE nvidia_smi_log SYSTEM "nvsmi_device_v8.dtd">`, but it should not be a problem, since the latter works (1 gpu node), while the first not (2 gpu inner nodes).

**Comment by Leonidas-from-XIV** [comment]
What is the error in `err` in the failing case?

**Comment by loretoparisi** [comment]
@Leonidas-from-XIV so the error was `null` or `undefined`. At the end I was able to parse using a combination of `xmldom` and some xml2js old browser library. See [here](http://stackoverflow.com/questions/42769303/nvidia-smi-json-output).
