### ISSUE TITLE
Error: Non-whitespace before first tag. Line: 0 Column: 1 Char: R at error 

### ISSUE THREAD

**Issue by iwish0** [Leonidas-from-XIV/node-xml2js#368]
I 'm using angular2 and my version of xml2js is  0.4.17.

I think that this issue is supposed to fixed but when i attempt to consume some data from an xml file or from a web service, i get this issue and didn't find a way to solve it.

for example:

```
getMovieInXMl():Observable<movie>{
         return this.http.get('http://www.omdbapi.com/?t=MATRIX&r=xml')
                .map(this.extractData);              
  }
```

```
private extractData(res: Response) {
  let body;    
  var parser = new Parser();
    
parser.parseString(res,(err,result)=>{
    console.log(err) // display the message : Error: Non-whitespace before first tag. Line: 0 Column: 1 Char: R at error 
    body=result; // result is undefined
   })
     return body;
}
```

**Comment by Leonidas-from-XIV** [comment]
Downloading that file to `matrix.xml`, the following code parses the file just fine, with the current version of `xml2js`:

```javascript
const p = require('xml2js').parseString;
const fs = require('fs');

fs.readFile('matrix.xml', function(err, data) {
	p(data, function (err, data) {
		console.log(data);
	});
});```

**Comment by iwish0** [comment]
Thank you for your answer.  Your example also works for me. I don't understand  but i assume that the problem comes from the way i use it with angular2, so i  close the issue.

**Comment by dasyah** [comment]
> ```js
> const p = require('xml2js').parseString;
> ```

its work If I use fs.readFile

but its giving me error Error: Non-whitespace before first tag If I use  https.get

I copy the output from  https.get and paste to txt file and save it as xml file,
then read it using fs.readFile and just work fine but wont work if using url

need solution:(

**Comment by dasyah** [comment]
> 
> 
> Downloading that file to `matrix.xml`, the following code parses the file just fine, with the current version of `xml2js`:
> 
> ```js
> const p = require('xml2js').parseString;
> const fs = require('fs');
> 
> fs.readFile('matrix.xml', function(err, data) {
> 	p(data, function (err, data) {
> 		console.log(data);
> 	});
> });
> ```


its work If I use fs.readFile

but its giving me error Error: Non-whitespace before first tag If I use https.get

I copy the output from https.get and paste to txt file and save it as xml file,
then read it using fs.readFile and just work fine but wont work if using url

need solution:(
