### ISSUE TITLE
Non-whitespace before first tag. Line: 0 Column: 1 Char: [

### ISSUE THREAD

**Issue by Sharan00** [Leonidas-from-XIV/node-xml2js#371]
Hi,

I am still getting Non-whitespace before first tag issue.  But I am reading my xml from postman post req.body which is in application/xml format.

I got   "version": "0.4.17" version of xml2js, but node version is 4.5.0

    var parser =  new xml2js.Parser({explicitArray : false});
      parser.parseString(req.body, function (err, result) {
        console.dir(result);
        console.log('Done');
      });

I got the right result when if used fs to read the file, which had the same xml from req.body

Please help.

**Comment by Leonidas-from-XIV** [comment]
Can you show the hexdump of the first couple of characters of `req.body`?

**Comment by Sharan00** [comment]
27687474703a2f2f686c372e6f72672f66686972273eda20203c7

**Comment by Sharan00** [comment]
Never mind, I got it.  I looked in sax module and saw that it was converting an object to string and then parsing [object].

Thank you for getting back to me.
