### ISSUE TITLE
mergeAttrs not ignored when ignoreAttrs is false

### ISSUE THREAD

**Issue by vinhboy** [Leonidas-from-XIV/node-xml2js#372]
In the documentation, for `mergeAttrs`, it says that "This option is ignored if ignoreAttrs is false."

However, when I set `ignoreAttrs: false`

This

```xml
    <link href="google.com"/>
    <link href="yahoo.com"/>
```

Becomes

```json
    // mergeAttrs: false
    {link: [{ '$': { href: 'google.com' } },{ '$': { href: 'yahoo.com' } }]}
```

```json
    // mergeAttrs: true
    {link: [ { href: 'google.com' }, { href: 'yahoo.com' }]}
```

Personally, this works out well for me because that's what I want. But the documentation is misleading. 

It would be even better if it did this

```json
    // mergeAttrs: true
    {link: { href: ['google.com', 'yahoo.com'] }}
```

May be related to: https://github.com/Leonidas-from-XIV/node-xml2js/issues/367

**Comment by jcsahnwaldt** [comment]
The documentation is wrong. It should read:

This option is ignored if `ignoreAttrs` is `true`.

**Comment by Leonidas-from-XIV** [comment]
Fixed, thanks for pointing it out.
