### ISSUE TITLE
Upgrade to non-locked dependency (xmlbuilder) is forcing node >= 6.0.0

### ISSUE THREAD

**Issue by PresNCode** [Leonidas-from-XIV/node-xml2js#382]
One of the dependencies (xmlbuilder) just got bumped from 8.2.2 to 9.0.0; as per [this closed issue](https://github.com/oozcitak/xmlbuilder-js/issues/156) one of the changes causes crashes if your node version is < 6.0.0. Since xml2js itself doesn't require that node version, the dependency should be locked here to 8.2.2.

**Comment by Leonidas-from-XIV** [comment]
The new xmlbuilder (9.0.1 specifically) fixes some issues, so we depend on it now. Surprisingly, the tests still pass even on Node 0.10.

I'd be interested in a test which makes the old Node versions fail though.
