### ISSUE TITLE
white space surrounding an attribute?

### ISSUE THREAD

**Issue by michaeled** [Leonidas-from-XIV/node-xml2js#384]
Is it possible to preserve the white space surrounding an attribute?

**Comment by Leonidas-from-XIV** [comment]
An attribute value?

**Comment by michaeled** [comment]
The attribute name, so preserving tabs and newlines characters between attributes are preserved.

**Comment by Leonidas-from-XIV** [comment]
No, these are not part of the tree that XML parses to.
