### ISSUE TITLE
Outdated version on npm

### ISSUE THREAD

**Issue by leonard-thieu** [Leonidas-from-XIV/node-xml2js#387]
Looks like the current package on npm is outdated.

(2016-07-05) https://unpkg.com/xml2js@0.4.17/lib/
vs
(2017-03-28) https://github.com/Leonidas-from-XIV/node-xml2js/tree/af83e313790d28e65ad0f99324a6fbdef9da54fd/lib

Could a recent version be published?

**Comment by Leonidas-from-XIV** [comment]
I've published 0.4.18 yesterday, which is a rollup release of whatever happened in the last year.
