### ISSUE TITLE
Should parsing processors be passed to constructor?

### ISSUE THREAD

**Issue by davidtheclark** [Leonidas-from-XIV/node-xml2js#389]
The docs right now suggest you pass this processor object as a second argument to `parseString`, between the XML and the callback: https://github.com/Leonidas-from-XIV/node-xml2js/blob/b5e351a6154dc989f635c6206a7680cebb39993e/README.md#processing-attribute-tag-names-and-values

However, I'm noticing that these processors only work if pass them to the constructor, e.g.

```js
const xmlParser = new xml2js.Parser({
  attrNameProcessors: [reactifyAttribute]
});
```

Are the docs wrong? Or am I misunderstanding?

**Comment by brentahiti** [comment]
`parseString` actually instantiates a `xml2js.Parser` object under the hood with the options passed, so there shouldn't be any problem
hope this is not too too late for an answer

**Comment by davidtheclark** [comment]
@brentahiti: It's been a while, but I think my original problems was that I tried `parseString()` with the options and they didn't work.

**Comment by Leonidas-from-XIV** [comment]
This should work, since there is no processing whatsoever on the options, it just passes them on as-is, as you can see in the source code for `parseString`: https://github.com/Leonidas-from-XIV/node-xml2js/blob/b5e351a6154dc989f635c6206a7680cebb39993e/src/parser.coffee#L258
