### ISSUE TITLE
Getting Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: error in xml2js parsing

### ISSUE THREAD

**Issue by iitrsachin** [Leonidas-from-XIV/node-xml2js#390]
I am using following code to convert XML into Js object but it's not working for me. I tried so many solutions from the internet but did not get the right solution. xml2js version - 0.4.17

const parser = new xml2js.Parser({ explicitArray: false, });
const data = "<title>Hello, Mr. Peter</title>";
parser.parseString(data, (err, result) => {
               console.log(result);
            });

Please do some needful.

**Comment by Leonidas-from-XIV** [comment]
What encoding are you using in your JS file? Are you sure it is UTF-8?

**Comment by iitrsachin** [comment]
Hi Leonidas,
Thank you for the reply.
I checked with utf8.js to encode string 
const someText = utf8.encode(data);

but still getting same error.

**Comment by SyntonicStudios** [comment]
I tried parsing an XML file in ANSI, UTF8 and Unicode and all of them still give this error message. I'm running a front-end project on Windows if that matters. 

Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �

**Comment by iitrsachin** [comment]
If I send data as a function parameter then it's not working and giving "Non-whitespace before first tag" error but it's working when I define data variable inside the function. 

@Leonidas-from-XIV what should I do to fix it?

**Comment by Leonidas-from-XIV** [comment]
Can you show me an example that works for you and one which does not?

**Comment by iitrsachin** [comment]
Thank you @Leonidas-from-XIV. I used data.toString('utf8') and working for me.

**Comment by marcelolfilho** [comment]
did not work :(

**Comment by dobeerman** [comment]
still not works ;(

**Comment by Leonidas-from-XIV** [comment]
Posting a self-contained reproducible example would be much more helpful.

**Comment by dobeerman** [comment]
@Leonidas-from-XIV gist here https://gist.github.com/dobeerman/f1e8a9f51f6787fa44e3d9563dde90f7

**Comment by Leonidas-from-XIV** [comment]
Thanks but this is not self-contained, I'd have to write a lot of code around it to run it.
