### ISSUE TITLE
xml2js.Parser is not a function

### ISSUE THREAD

**Issue by pchanley** [Leonidas-from-XIV/node-xml2js#393]
error occurs in the following code:
var xml2js = require('xml2js');
      var parser = new xml2js.Parser();
      parser.parseString(data, function (err, result) {
        console.dir(result);
        console.log('Done');
      });

**Comment by adamvoss** [comment]
@pchanley I am not able to reproduce this.  I set `data = ""` and ran your exact code above in the node REPL.  No error occurred.

**Comment by Leonidas-from-XIV** [comment]
`""` is invalid XML and will now (0.4.18) trigger errors.
