### ISSUE TITLE
0.4.18 breaking change

### ISSUE THREAD

**Issue by jamesabc** [Leonidas-from-XIV/node-xml2js#399]
I think b9b44e08e13278d0f81d46d0316d728e96d6352e is a breaking change.  At least, we got unit test failures in CI after updating our shrinkwrap.  Is it possible this commit could be released in a semver minor bump (0.5.0) and reverted for 0.4.x, to prevent breaking users that pin with `^` or `~` in package.json?

**Comment by Leonidas-from-XIV** [comment]
According to (the NPM docs)[https://docs.npmjs.com/cli/unpublish] it is impossible to unpublish things.

**Comment by jamesabc** [comment]
Hi, thanks for the very rapid response!

What I would probably try is to make a 0.4.x branch, add a commit to revert that one change, and tag a 0.4.19 release from it.  Then, anyone upgrading from <=0.4.17 that has pinned with `^` will go straight to 19, which doesn't have the breaking change.  Then, a 0.5.0 release from master for those that do want/depend on the new behaviour.

It is still a headache tho, and it might break some users that have installed 0.4.18 and pinned with
 `^`, so I am not making any demands 😄 .  For now, my project is fixed by pinning 0.4.17 exactly so you may want to just close this.

**Comment by Leonidas-from-XIV** [comment]
I've just reverted this particular merge and released 0.4.19 from master.
