### ISSUE TITLE
build XML with attributes

### ISSUE THREAD

**Issue by alexey2baranov** [Leonidas-from-XIV/node-xml2js#401]
Hello ! How can we build XML with attributes?
Very short manual about builder https://github.com/Leonidas-from-XIV/node-xml2js#xml-builder-usage does not cover this question.

Thanks

**Comment by impromptu100** [comment]
@alexey2baranov As per my understanding xml2js uses xmlbuilder-js for building xml (or modifying it). 

Refer to https://github.com/oozcitak/xmlbuilder-js 

`item.att('key', 'value');`

to add attributes

**Comment by dkiltyhc** [comment]
From the unit tests use the following syntax for your input JSON object:
'$' -to identify the attribute(s)
'_ ' - to identify the inner text value

For example:
let temp = {
      'test': {
        'foo': 'bar',
        'generator': {'$':{'uri': 'http://www.example.com/', 'version': '1.0'}, '_': 'Example Toolkit'},
      }
    };
Will  build the following XML:
<test>
  <foo>bar</foo>
  <generator uri="http://www.example.com/" version="1.0">Example Toolkit</generator>
</test>

**Comment by unional** [comment]
```ts
import xml2js = require('xml2js')

const b = new xml2js.Builder({ attrkey: '@' })
test('s', () => {
  const actual = b.buildObject({ a: { '@name': 'abc' } })
  console.log(actual)
})
```
produces
```xml
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <a>
      <@name>abc</@name>
    </a>
```

I think this code does not work correctly:
https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/src/builder.coffee#L45-L50

**Comment by jcsahnwaldt** [comment]
@unional The attrkey is not a prefix for the attribute name (as in XPath). Instead, your object should have a property with the name attrkey whose value should be an object containing all the attributes:

{ a: { '@': { name: 'abc' } } }

**Comment by jcsahnwaldt** [comment]
I think this issue can be closed.

**Comment by Leonidas-from-XIV** [comment]
In general I should probably document the input and output formats a bit better. But yeah.
