### ISSUE TITLE
Combine mergeAttrs and attrkey 

### ISSUE THREAD

**Issue by kolis** [Leonidas-from-XIV/node-xml2js#406]
I would like to have node attributes directly as children, but with prefix. Eg
```xml
<foo myAttr="1">
</foo>
```
Would produce
```js
foo.$myAttr == "1"
```
Right now I can get either `foo.$.myAttr`, or `foo.myAttr`, by using `attrkey` and `mergeAttrs` options. But the combination of these should be `foo.$myAttr` I think!

**Comment by Leonidas-from-XIV** [comment]
Sorry, for now you'll have to live with the one extra character, it does not justify breaking compatibility or adding another option.
