### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wilywork** [Leonidas-from-XIV/node-xml2js#410]
i have a Xml with 70k of registers, 
When I transform xml to json I get this error  "RangeError: Maximum call stack size exceeded"
line errror try cacth..
https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/parser.js#L303

**Comment by wilywork** [comment]
solved, my code in callback...
`
xmlToJson = require('xml2js').parseString;
xmlToJson(body, function (err, soapRequest) {
// my code maximum call....
 });
`

**Comment by jim1795** [comment]
@wilywork Can you explain how you solved it. I get this while building the XML.

**Comment by Christilut** [comment]
Incase someone comes across this: in my case it was because I had passed an array by reference which for some reason xml2js didn't like. I solved it by simply doing `obj.items = oldObj.items.map(x => x)`
