### ISSUE TITLE
Question on special character & with Angular build

### ISSUE THREAD

**Issue by bayy** [Leonidas-from-XIV/node-xml2js#411]
I am using xml2js to save and load a xml file to a server with Angular 5. I encountered a problem with char & in an angular production environment only. 

I have a text field with value 'a & b', which is saved to the server as `a &amp; b` using xml2js. When loading the data from the server, it works on a local environment. However, on a production server, it will complain that "Cannot read property 'toLowerCase' of undefined" with the following code.
```
this.parser.parseString(xmlSource, (err, result) => {
      allNodes = this.parseXML(result.x);
});
```
The err in the above code shows stack trace of minified code. 
```
    TypeError: Cannot read property 'toLowerCase' of undefined
    at L (sax.js:913)
    at o.write (sax.js:1485)
    at h.parseString (parser.js:322)
    at h.parseString (parser.js:5)
    at e.fromXML (xml.service.ts:52)
```
line 912 parser.entity returns null, though on local environment, it is 'amp'
<img width="549" alt="screen shot 2018-01-12 at 4 33 58 pm" src="https://user-images.githubusercontent.com/2373656/34899497-88990532-f7b6-11e7-9d79-da3721061601.png">

Any help will be greatly appreciated.

**Comment by bayy** [comment]
This turned out to be a bug in UglifyJS https://github.com/mishoo/UglifyJS2/issues/2783. It has been fixed.

**Comment by priyankairislogic** [comment]
I am facing exact same issue with xml2js in ionic 2 when I do production build. Does anyone know how to fix this? App runs without any error in dev environment

**Comment by priyankairislogic** [comment]
Fixed it by using uglifyjs3.3.4
