### ISSUE TITLE
How to converter GMT date

### ISSUE THREAD

**Issue by zonglu233** [Leonidas-from-XIV/node-xml2js#413]
Hello.this is my json data , but it can't converter to xml.The type is date and it is  GMT

{
  "date": Fri Jan 05 2018 14:55:51 GMT+0800 (中国标准时间)
}

**Comment by Leonidas-from-XIV** [comment]
Can you post a minimal, runnable example with the error that you're getting?

**Comment by Leonidas-from-XIV** [comment]
Closed due to inactivity. Feel free to reopen with a minimal failing example @zonglu233.
