### ISSUE TITLE
What error is this?

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [Leonidas-from-XIV/node-xml2js#418]
hi!
to load the file https://rawgit.com/bpmn-io/bpmn-js-examples/master/starter/diagram.bpmn

and this error message appears

Error: required args <xml=string>
    at error (parser.js:12)
    at Saxen.parse (parser.js:237)
    at eval (reader.js:803)
    at eval (baseDelay.js:18)

**Comment by jcsahnwaldt** [comment]
Since xml2js doesn't use Saxen, I don't think this error is caused by xml2js. @carvalhoviniciusluiz You should probably report the issue here: https://github.com/nikku/saxen

**Comment by jcsahnwaldt** [comment]
I think this issue can be closed.
