### ISSUE TITLE
How to build empty tags?

### ISSUE THREAD

**Issue by akaNightmare** [Leonidas-from-XIV/node-xml2js#419]
I have some code:
```js
const xml2js = require('xml2js');
const builderXML = new xml2js.Builder();
console.log(
    builderXML.buildObject({
        test: [],
    }),
);
```
and I expect this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<test></test>
```
but received:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<test/>
```

**Comment by Leonidas-from-XIV** [comment]
Yes, according to the specification of XML this is exactly the same and [self-closing tags should be preferred](https://www.quora.com/Are-self-closing-tags-valid-in-XML).

**Comment by magendhiran** [comment]
refer https://github.com/Leonidas-from-XIV/node-xml2js/issues/394

you may use const builder = new xml2js.Builder({renderOpts: { 'pretty': true, 'indent': ' ', 'newline': '\n', allowEmpty: true }});
