### ISSUE TITLE
Escape (somehow) invalid chars in tag content

### ISSUE THREAD

**Issue by ybrodsky** [Leonidas-from-XIV/node-xml2js#425]
I am trying to integrate a webservice not very well done, so I am receiving some xml like this:

`<sometag> this is the tag content and has a < char </sometag>`
without cdata.

When trying to parse this it throws invalid char error. Is there anything I can do?

**Comment by Leonidas-from-XIV** [comment]
You can escape the invalid XML into `&lt;` or wrap the entire text node in `CDATA` which might be the easier thing to do.

**Comment by ybrodsky** [comment]
But how do I get there in the first place. Imagine I have something like this.
`
  <root>
    <childOne>Hello there</childOne>
    <childTwo> I am retarded < ho ho ho (Frieza's laugh)</childTwo>
  </root>
`

Now, before any parsing this is merely a string. How do I go about wrapping childTwo content in CDATA? or escape it's content. I could regex the shit out of it and do it, but it's quite a big piece of xml.

**Comment by Leonidas-from-XIV** [comment]
I see that it is a problem @ybrodsky but I also see that it is a problem that `xml2js` can't do much about. I think `xml2js` *requiring* well-formed XML is not to much to ask of (after all, it is called `xml2js`, not `random text with < and > 2js`), so if you need to parse things that aren't XML you'll have to do some preprocessing. Sorry, but `xml2js` can't just handle every single case.

**Comment by ybrodsky** [comment]
This was some time ago. After writing here I complained with the people who maintains that service and they replied: 'we chose to do it that way'. Like....wtf you chose to do it wrong?
No point discussing with that kind of people. 

Anyway thanks for the follow up
