### ISSUE TITLE
$ and _ in json

### ISSUE THREAD

**Issue by specialdeveloper** [Leonidas-from-XIV/node-xml2js#432]
Is there a way to get rid of there two when parsing the xml file?
    mergeAttrs: true somehow works for $ but for _?

**Comment by jchenHPA** [comment]
Per my test, mergeAttrs: true does get rid of the $. But it also converts all attributes to a array.
Is there a way not to generate the $ for child node?

**Comment by jchenHPA** [comment]
Read the source code and it turns out that the combination of mergeAttrs and explicitArray in option can get rid of the $. {mergeAttrs : true, explicitArray: false}

**Comment by jcsahnwaldt** [comment]
I think the issue can be closed.
