### ISSUE TITLE
Error: Invalid character entity when use !ENTITY

### ISSUE THREAD

**Issue by Yookkee** [Leonidas-from-XIV/node-xml2js#443]
Is it possible to parse the following code, or any which uses External Entities using parseString function?
![capture](https://user-images.githubusercontent.com/15655261/38469827-a00657ce-3b63-11e8-85e7-98b43166b3b7.PNG)
It always output errors like this 
```
Error: Invalid character entity
Line: ...
Column: 57
Char: ;
```

**Comment by julimen5ml** [comment]
Hi @Yookkee, did you find a way to escape that error?

**Comment by jcsahnwaldt** [comment]
sax-js ignores custom DTD `<!ENTITY ...>` definitions: "It's possible to define additional entities in XML by putting them in the DTD. This parser doesn't do anything with that." https://github.com/isaacs/sax-js#regarding-doctypes-and-entitys Thus when a custom entity like `&xxe;` occurs in the XML, the parser throws an error.

**Comment by jcsahnwaldt** [comment]
Here's an ugly workaround:

```javascript
let parser = new xml2js.Parser();
parser.saxParser.ENTITIES.xxe = 'whatever';
let js = parser.parseString('<foo>&xxe;</foo>');
console.log(js);
```
Result:
```javascript
{ foo: 'whatever' }
```
You shouldn't use this in production code though. `parser.saxParser` is an undocumented property that may go away any moment.
