### ISSUE TITLE
Error 503 No healthy backends

### ISSUE THREAD

**Issue by adefirmanf** [Leonidas-from-XIV/node-xml2js#447]
It came from https://www.npmjs.com/package/xml2js. There's something wrong about npm or probably this repository. 
![image](https://user-images.githubusercontent.com/23324722/38805591-831db0e2-41a0-11e8-929c-7f5968bd44e1.png)

Can you explain it what happened? But, during npm install there's nothing error. It just make user thinking this repository has been shut down cause this issue. 

Thanks

**Comment by Leonidas-from-XIV** [comment]
Where do you see that? When I click your link it is all fine.

It seems like the Varnish server on npmjs.com went for a smoke or something.

**Comment by adefirmanf** [comment]
It's weird. recently, I change my proxy into JP and there's nothing wrong about that. But when I change back to original proxy it's back into that issue. 

[Edited]
This issue is coming from my ISP, not only this repository but all of them who published to npm.js showing the same page. 

[Solve]
Using proxy or change ISP

Sorry for misunderstanding. Going close this issue now.  Thank you
