### ISSUE TITLE
xml minifier?

### ISSUE THREAD

**Issue by draschke** [Leonidas-from-XIV/node-xml2js#448]
Hi, 
is there a way to minify the xml text like 
http://www.webtoolkitonline.com/xml-minifier.html it does?

Thanks

**Comment by jcsahnwaldt** [comment]
What do you want to do? Could you post an example? I played around with http://www.webtoolkitonline.com/xml-minifier.html a bit, but I can't really tell what it does...

**Comment by draschke** [comment]
yes, this is what I did and came to almost the same result.
thanks!
