### ISSUE TITLE
Is there a way to skip scientific notation when using parseNumbers

### ISSUE THREAD

**Issue by steveshourds** [Leonidas-from-XIV/node-xml2js#453]
parseString(r.Response, { explicitArray: false, valueProcessors: [parseNumbers] }, function (err, result) {..}

Values like "12E01" is a string in the r.Response data, but your parser is converting to a number 12.

Is there an option to skip scientific notation converting when using parseNumbers?

If not, can you point me in the right direction to disable for now?

**Comment by steveshourds** [comment]
Found the processor code and changed it to:

  exports.parseNumbers = function (str) {
    if (!isNaN(str) && isFinite(str) && str.indexOf('E') === -1 && str.indexOf('e') === -1) {
      str = str % 1 === 0 ? parseInt(str, 10) : parseFloat(str);
    }
    return str;
  };

What's the best way to wrap this into an option and submit into the main code base?

**Comment by steveshourds** [comment]
Ok, great, I'll do it myself, just seemed like it might be useful as a simple option.. ignoreScientificNotation  (like normalize or trim)..

Thanks so much

**Comment by jcsahnwaldt** [comment]
I guess this can be closed, right?

**Comment by steveshourds** [comment]
Yes close it, I call the following code on specific fields that I want to type as number

    parseNumber(value) {
        let typ = typeof value
        if (typ === 'number' || (typ === 'string' && value.toUpperCase().indexOf('E') !== -1)) { return value }
        if (!isNaN(value) && isFinite(value)) {
            value = value % 1 === 0 ? parseInt(value, 10) : parseFloat(value);
        }
        return value
    }

Thanks!
