### ISSUE TITLE
Is it Support hapi.js framework?

### ISSUE THREAD

**Issue by SantoshSKhavekar** [Leonidas-from-XIV/node-xml2js#455]
Hi,
I wanted to know that Is it Support hapi.js framework or not?

**Comment by Leonidas-from-XIV** [comment]
After looking up what Hapi is: it is completely orthogonal to Hapi.

**Comment by jcsahnwaldt** [comment]
I think the issue can be closed.

**Comment by Leonidas-from-XIV** [comment]
I agree
