### ISSUE TITLE
documentation: explain how to add xmlns attributes

### ISSUE THREAD

**Issue by jcsahnwaldt** [Leonidas-from-XIV/node-xml2js#464]
It's simple, but maybe not obvious for many users:
```javascript
$: {
  'xmlns': 'http://foo.com'
} 
```
See issue https://github.com/Leonidas-from-XIV/node-xml2js/issues/121 , https://github.com/Leonidas-from-XIV/node-xml2js/issues/121#issuecomment-312881536 and https://github.com/Leonidas-from-XIV/node-xml2js/issues/121#issuecomment-396086909 for more details.

**Comment by Leonidas-from-XIV** [comment]
That's a good idea. Can you submit a PR?

**Comment by jcsahnwaldt** [comment]
Done: https://github.com/Leonidas-from-XIV/node-xml2js/pull/465

**Comment by Leonidas-from-XIV** [comment]
Merged, thanks!

**Comment by jcsahnwaldt** [comment]
Cool, thanks!
