### ISSUE TITLE
how to against XXE attacks

### ISSUE THREAD

**Issue by JersonZhengBijie** [Leonidas-from-XIV/node-xml2js#469]
hello!!! My project is using xml2js module, but, i have a  question, Does the module against XXE attacks? What shall I do? thanks!!!

**Comment by lukywong** [comment]
it seems that it ignores custom DTD #443

**Comment by JersonZhengBijie** [comment]
That means I don't need to do anything? the module is safe? @lukywong

**Comment by boostbob** [comment]
got it~

**Comment by JersonZhengBijie** [comment]
thanks @finian
