### ISSUE TITLE
Add support for sax 'strictEntities' option

### ISSUE THREAD

**Issue by ThomasVuillaume** [Leonidas-from-XIV/node-xml2js#471]
Hi there,

I just was looking arround to see if somewhere we could disable external entities during parsing, and it came out that we could do this by setting "strictEntities" to true in sax parser.

Goal : be sure to avoid XXE attacks

**Comment by atlantismonk** [comment]
very agree.

**Comment by xudongsxd** [comment]
how to use?@ThomasVuillaume

**Comment by xudongsxd** [comment]
https://github.com/Leonidas-from-XIV/node-xml2js/issues/415

**Comment by ThomasVuillaume** [comment]
@xudongsxd nice link !

I think we can thus close this
