### ISSUE TITLE
Update deprecated:`events.EventEmitter` to `events` in parser

### ISSUE THREAD

**Issue by arorayash** [Leonidas-from-XIV/node-xml2js#492]
As far as I'm aware the `events.EventEmitter` has been deprecated in favor of simply `events`. 
However, `events.eventEmitter` is still being used in `/src/parser.coffee`

**Comment by Leonidas-from-XIV** [comment]
Do you have a source for that? In the current documentation it does say `events` (so I think this change makes sense in general) but no note about any deprecation or when that was even introduced.

**Comment by Leonidas-from-XIV** [comment]
Anyway, I tested it on the currently supported versions of Node and it works, so no reason not to merge it. Thanks!
