### ISSUE TITLE
Switch prefix for attrkey from "$" to a different one

### ISSUE THREAD

**Issue by mario-liggiu** [Leonidas-from-XIV/node-xml2js#495]
We have observed that the default prefix "$" for the attribute key is conflicting with a (security) constraint with the MongoDB driver. In case data is persisted via the driver, this is rejected with the following message:
"Error: key $ must not start with '$'"

See example for a converted XML to JSON below:
```
<?xml version="1.0" encoding="utf-8"?>
<root myatt="test">
  <content>test content</content>
</root>

```

```
{
  root: {
    '$': {
      myatt: 'test'
    },
    content: ['test content']
  }
}
```

I know that there is the option to switch the attrkey of xml2js from the default prefix "$" to a different one. However I want to ask, whether it would make sense to map already the default prefix to a different character, as the converted JSON documents are getting potentially saved in a MongoDB.

I also would like to ask, whether there is a recommended character, if another character besides the default prefix "$" is used? Because I have seen in the documentation, that previously the character "@" was used, and in another case the character "#". Due to this, I would like to ask whether there is a specific reason why those were not used anymore.

**Comment by Leonidas-from-XIV** [comment]
The reason why `$` is used is because unlike `@` it is a valid identifier name, e.g. you can use it like `foo.$.bar` which is not possible with `@` which will turn to `foo['@'].bar` which adds a lot of noise. Similarly this is also why `_` is used. I left the option in to switch it back to the old mode but for most people direct access is probably more convenient.

**Comment by mario-liggiu** [comment]
Thanks for the explanation. Any recommendation from your experience what character should/could be used instead of the dollar character?
