### ISSUE TITLE
Bug: non-strict parsing mode converts tag-names to UPPERCASE.

### ISSUE THREAD

**Issue by Domvel** [Leonidas-from-XIV/node-xml2js#501]
### Bug-Report

I wondering why are the tag-names of a parsed xml UPPERCASE formatted?

Input: 
```xml
<PascalCase>Foo</PascalCase>
```

Output:
```json
{ "PASCALCASE": ["Foo"] }
```

And btw. why is the value wrapped to an array? Ok, I think because a tag could contain tag-nodes as childs. ... But why uppercase? 

xml2js 0.4.19 (latest)
@types/xml2js 0.4.3 (latest)

**Comment by Leonidas-from-XIV** [comment]
I don't think it should uppercase. Can you post a minimal example on how this happens?

The result is in an array because you might potentially have multiple things in your tag, like `<PascalCase><Haskell/><Idris/></PascalCase>` so it stays consistent and is an array.

**Comment by Domvel** [comment]
Thanks for fast response. [See example](https://stackblitz.com/edit/angular-xml2js?embed=1&file=src/app/app.component.ts)

**Comment by Domvel** [comment]
I see if I remove `strict: false` it works.

**Comment by Leonidas-from-XIV** [comment]
Can you make a minimal example which does not involve dependencies outside of xml2js, like Angular?

**Comment by Domvel** [comment]
[Blank JavaScript Example](https://stackblitz.com/edit/js-xml2js?embed=1&file=index.js)

Note: The dependencies `timers`, `string_decoder`, 'events' are required to work with `xml2js` (node).

**Comment by Leonidas-from-XIV** [comment]
That's interesting. Looks like the underlying parser, sax-js is uppercasing tag names for some reason…

**Comment by Domvel** [comment]
So, this is an issue of [the sax-js repositrory](https://github.com/isaacs/sax-js) not xml2js?

**Comment by Leonidas-from-XIV** [comment]
I assume so, since we never actually do anything with the strict option except for passing it to `sax-js`:

https://github.com/Leonidas-from-XIV/node-xml2js/blob/0f0a2980b3db5366b3d50e4d0da422cb7af100c9/src/parser.coffee#L70-L74

**Comment by Domvel** [comment]
Ok, your project xml2js uses the `sax` version `0.6.0`, but the latest is `1.2.4`. Maybe an update will fix this? But wait ... take a look to [this](https://github.com/isaacs/sax-js/issues/37) issue on sax repo. I do not think that this gonna be changed.
