### ISSUE TITLE
Lock major version of all dependencies.

### ISSUE THREAD

**Issue by grushikhin** [Leonidas-from-XIV/node-xml2js#507]
Hello, guys!
My application was accidentally broken last week due to a major update of `xmlbuilder`.
We use the latest version of `Restler`HTTP client (3.4.0), which depends on `xml2js@0.4.0`, which depends on `xmlbuilder@>=0.4.2` and the latest version of `xmlbuilder` is `10.0.0`.
I know that in the latest version of `xml2js` you locked 10'th version of `xmlbuilder`, it's fine, but you still depend on another dependency `sax` as `>=0.6.0`, which actual version is `1.2.4`.
Any breaking changes in `sax` dependency can break `node-xml2js` at any time, 
so, I strongly recommend you to lock major versions of each your dependencies and follow `semver`.
Thank you!

**Comment by Leonidas-from-XIV** [comment]
That sounds reasonable. Can you submit a PR with your proposed changes.

**Comment by grushikhin** [comment]
Will do :)

**Comment by Leonidas-from-XIV** [comment]
Does the committed lock-file solve your issues?

**Comment by Leonidas-from-XIV** [comment]
I've committed the `npm` generated lock file.

**Comment by knoxcard** [comment]
Even better solution was proposed here and appears to already be implemented or extremely close to....
https://github.com/Leonidas-from-XIV/node-xml2js/issues/517

grushikhin - close issue?
