### ISSUE TITLE
Parse failed when attribute string with &

### ISSUE THREAD

**Issue by zhangjiangshan** [Leonidas-from-XIV/node-xml2js#509]
Example:
` <view attr="a&b"/>`

version: 0.4.19
node_version: v10.13.0

**console error :** 
`Error: Invalid character in entity name
Line: 7
Column: 36
Char: &`

**Comment by Leonidas-from-XIV** [comment]
It is not well-formed XML so the failure makes sense. You need to use `&amp;`.
