### ISSUE TITLE
[Feature Request] Updating Status

### ISSUE THREAD

**Issue by deeyonn** [Leonidas-from-XIV/node-xml2js#513]
Hello, I use xml2js.Parser() on some of my xml files that are 500MB, and it takes a good 60 seconds for the process to complete. Is it possible to add a feature like a callback function I can give so that it updates on its status every few or so % parsed?

**Comment by Leonidas-from-XIV** [comment]
I theory it could send some kind of updates (since it is based on a SAX parser) but it can't tell you how many % since it doesn't know how many items will still come in the future.

**Comment by paul-uz** [comment]
This is something that would be really useful to me as well.

Would you be able to calculate an estimate and refine it over time?

**Comment by paul-uz** [comment]
@deeyonn why did you close this? Did you figure out how to achieve what you wanted?

**Comment by deeyonn** [comment]
> @deeyonn why did you close this? Did you figure out how to achieve what you wanted?

Nope it's been 3 years and I've long moved on

**Comment by paul-uz** [comment]
> > @deeyonn why did you close this? Did you figure out how to achieve what you wanted?
> 
> Nope it's been 3 years and I've long moved on

What are you using now?

**Comment by deeyonn** [comment]
> > > @deeyonn why did you close this? Did you figure out how to achieve what you wanted?
> > 
> > 
> > Nope it's been 3 years and I've long moved on
> 
> What are you using now?

Nothing, I've just stopped working with 500MB files and moved on with life

**Comment by paul-uz** [comment]
> > > > @deeyonn why did you close this? Did you figure out how to achieve what you wanted?
> > > 
> > > 
> > > Nope it's been 3 years and I've long moved on
> > 
> > What are you using now?
> 
> Nothing, I've just stopped working with 500MB files and moved on with life 

I see. Well good luck!
