### ISSUE TITLE
xml2js is not compatible with node.js v10

### ISSUE THREAD

**Issue by manishaa603** [Leonidas-from-XIV/node-xml2js#533]
Hi,

i am using xml2js to convert XML data to JSON, i am getting following error
"DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."

Note: When i use it for Node.js v8 and below everything works fine, but it breaks only when i switch to v10.

can you please suggest some workaround.

**Comment by knoxcard** [comment]
Appears to  be a straightforward fix...
https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues

@Leonidas-from-XIV

**Comment by knoxcard** [comment]
@manishaa603 - can you post your xml2js code here?

**Comment by Leonidas-from-XIV** [comment]
This seems to be an issue that only the original poster has run into and not reported since. The reporter has not come back on this, so I'm going to close this for now since it is unreproducible.
