### ISSUE TITLE
Feature Request: Ignore specified object's attributes in XML Builder or ignore functions

### ISSUE THREAD

**Issue by pkozuchowski** [Leonidas-from-XIV/node-xml2js#543]
I need to serialize only part of JSON object to XML. The other attributes are metadata I need for processing.

I thought I could do that by hiding attributes in function, but the function is also serialized to xml using .toString() (I have doubts about usefulness of this behavior)

This is what I'd like to achieve:
```javascript
const builder = new xml2js.Builder({
    rootName: 'Something',
    ignoreAttrs = ['type']
});

const serializedObject = {
    attr1: '1',
    attr2: '2',
    type: 'metadataType',
    
    type2: function(){
        return 'metadataType'
    }
};
```
Expected:
```xml
<Something>
    <attr1>1</attr1>
    <attr2>2</attr2>
</Something>
```

Actual:
```xml
<Something>
    <attr1>1</attr1>
    <attr2>2</attr2>
    <type>metadataType</type>
    <type2>function (){
        return 'metadataType'
    }</type2>
</Something>
```

Alternatively, processor functions for builder would be nice.

**Comment by predam** [comment]
any news on this?
