### ISSUE TITLE
Can I use an xslt-file with xml2js?

### ISSUE THREAD

**Issue by ghost** [Leonidas-from-XIV/node-xml2js#550]
Hi I cannot find any information on the question in the title.

I have a bunch of xml-files that I want transformed in a node/express/ejs environment using the same xslt-file over and over again. 
(The files are all TEI-files containing marked up text)

I thought about using ejs and create a:

`<div class="container">
  <%  files.forEach(function (files) { %>
     <div>
		<%= <-- Enter transformed xml file here %>
	</div>
  <%  }); %>
	</ol>
</div>`
I hope you can clear this up? 
best wishes, 
K

**Comment by Omega-Ariston** [comment]
Could you state your idea more clearly? Like, in this scenario, what from of input and output are you expecting? :)

**Comment by Leonidas-from-XIV** [comment]
Since the user was deleted in the meantime, I doubt we'll get much more information out of this.
