### ISSUE TITLE
Add sample XML

### ISSUE THREAD

**Issue by pmcavoy89** [Leonidas-from-XIV/node-xml2js#552]
Can you please add the sample XML to the `README` in the `XML Builder Usage` section?
https://github.com/Leonidas-from-XIV/node-xml2js#xml-builder-usage

**Comment by Leonidas-from-XIV** [comment]
Merged the PR by @Omega-Ariston, thanks.

**Comment by pmcavoy89** [comment]
Thanks! I appreciate this work.
