### ISSUE TITLE
How to disable escape on escaped characters?

### ISSUE THREAD

**Issue by AllanOricil** [Leonidas-from-XIV/node-xml2js#574]
Im passing a object that has a string that is already escaped and it is being escaped again.

Example:
````
{
"key":"&quot;a&quot;"
}
````

Result:

<key>&amp;quot;a&amp;quot;</key>

Could you explain the reason?
Im using this lib to escape my string https://www.npmjs.com/package/he and works perfectly. But when Im gonna display my object in xml your lib escapes again.

**Comment by RyanKeepRunning** [comment]
Hi mate how did you resolve this? I'm running into the same issue.

**Comment by phaseharry** [comment]
+ 1

**Comment by AllanOricil** [comment]
No idea what I did to solve this issue
