### ISSUE TITLE
error with latest node

### ISSUE THREAD

**Issue by jackkitley** [Leonidas-from-XIV/node-xml2js#578]
Hello

I cant install this package with the latest version of node installed.

`npm install -save xml2js libxmljs

> libxmljs@0.19.7 install /Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.7 and node@14.5.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-darwin-x64.tar.gz
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83" "--python=/usr/local/bin/python"
gyp ERR! cwd /Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/14.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/usr/local/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/14.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Applications/MAMP/htdocs/Node/automark_proxy_api/node_modules/libxmljs/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/usr/local/bin/python' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.19.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by Leonidas-from-XIV** [comment]
This issues is from libxmljs, not related to xml2js which does not feature any parts written in C.

**Comment by jackkitley** [comment]
> This issues is from libxmljs, not related to xml2js which does not feature any parts written in C.

Thanks. Sorry for that
