### ISSUE TITLE
Mocking xml2js with jest

### ISSUE THREAD

**Issue by anrolmar** [Leonidas-from-XIV/node-xml2js#604]
Hi.

I'm trying to mock xml2js library with jest in my unit tests, but I get the message, `Cannot find module 'xmls2js'`

I tried it, with `jest.mock('xmls2js');`

**Comment by Leonidas-from-XIV** [comment]
I have no idea about `jest` but the library is called `xml2js`, there is an `s` too much in your call, maybe that is the issue?

**Comment by anrolmar** [comment]
That's it. Sorry
