### ISSUE TITLE
Build size ~200kB ?

### ISSUE THREAD

**Issue by Glideh** [Leonidas-from-XIV/node-xml2js#618]
Is ~200kB the expected build size of the library ?
Seems quite big, is there a way to use a subset ?
Is it tree shakeable or something ?

_Good tools BTW, that works very well for me_

**Comment by Leonidas-from-XIV** [comment]
I checked the built JS files and they're about 22kB, nowhere near 200kB.

**Comment by Glideh** [comment]
I mean not zipped, I'm getting about 44kB zipped, I'm going to investigate further

**Comment by Leonidas-from-XIV** [comment]
Look in the `lib` folder, the files there are less than 22kB unzipped. If you compress them and get double the size than uncompressed then there is something wrong with your tools.

**Comment by Glideh** [comment]
Well the 160kB unzipped is including the dependencies, xml2js indeed takes only 20Kb
![Screenshot from 2021-07-26 14-48-54](https://user-images.githubusercontent.com/1119270/126991595-4ac10430-08b2-4e20-ae38-c845dd7fc58a.png)

So these 160kB including dependencies are expected ?

**Comment by Leonidas-from-XIV** [comment]
Yes, I have no control about the size of the dependencies. Future releases are planned to get rid of xmlbuilder but that's a glacial work in progress.

**Comment by Glideh** [comment]
Ok at least my webpack settings are not wrong :)
Thx for your time.
