### ISSUE TITLE
wrong release version on yarn registry

### ISSUE THREAD

**Issue by dantxal** [Leonidas-from-XIV/node-xml2js#648]
Me and my team use yarn for managing our node packages.

And turns out the version 0.4.23 is outdated on those registries.

To be a bit more specific the code for applying the emptyTag value is wrong and won't let us use a function that returns undefined for example:

```js
...
          if (isEmpty(obj)) {
            obj = _this.options.emptyTag !== '' ? _this.options.emptyTag : emptyStr;
          }
...
```

As a workaround for now, I've used the github repo uri in "package.json".

I would appreciate if you could update the package on yarn.

UPDATE: Went ahead and decided to create a fork and link it instead of the original repo. :)

**Comment by Leonidas-from-XIV** [comment]
Looks like a problem with Yarn to me: #676
