### ISSUE TITLE
Yarn registry latest tag

### ISSUE THREAD

**Issue by leeferfeefer** [Leonidas-from-XIV/node-xml2js#676]
@Leonidas-from-XIV Looks like the yarn registry still states that the latest is 0.4.23. Is this an issue with tagging? Is this something you can fix?

https://yarnpkg.com/package/xml2js

**Comment by Leonidas-from-XIV** [comment]
I have no idea, I do not use yarn, I don't know where and how they get the data from.

**Comment by Leonidas-from-XIV** [comment]
It currently states

> New packages and versions may not show up in this interface due to an ongoing npm incident. Only search is affected, installs work as usual.

So I assume the issue is on the Yarn/NPM end and I can't really do much about this.
