### ISSUE TITLE
Screenshot (Jun 25, 2023 09:28:59)

### ISSUE THREAD

**Issue by ddiebold17** [Leonidas-from-XIV/node-xml2js#683]
![Screenshot_20230625-092859.png](https://github.com/Leonidas-from-XIV/node-xml2js/assets/121447862/29e063ce-0dae-44af-803e-95cc5af17784)

Identity 🆔 is being compromised stolen from me i live in Polk county Florida https doesn't work properly address is 1440 gay rd Lakeland FL 33811

**Comment by Leonidas-from-XIV** [comment]
Sorry to hear, I guess? Maybe contact the local authorities instead.
