### ISSUE TITLE
this.removeAllListeners is not a function

### ISSUE THREAD

**Issue by devmanzur** [Leonidas-from-XIV/node-xml2js#697]
![image](https://github.com/Leonidas-from-XIV/node-xml2js/assets/35005905/193bcb28-fecd-443f-b485-ca1fb61e7846)

![image](https://github.com/Leonidas-from-XIV/node-xml2js/assets/35005905/6d171bbb-2cb4-479e-a65f-42bc31f30496)

here is my function
```
async function parseXML(xmlContent: string): Promise<{ [key: string]: string }[]> {
  const parser = new xml2js.Parser({ explicitArray: true });
  const parsedData = await parser.parseStringPromise(xmlContent);

  const rowData = parsedData.DATAPACKET.ROWDATA[0].ROW;
  const rowsKeyValue: { [key: string]: string }[] = [];

  rowData.forEach((row: any) => {
    if (row != undefined) {
      const attributes: { [key: string]: string } = {};
      for (const key in row.$) {
        attributes[key] = row.$[key];
      }
      rowsKeyValue.push(attributes);
    }
  });

  return rowsKeyValue;
}

```

**Comment by jasonhutton-sd** [comment]
What was the fix?

**Comment by mamay12** [comment]
@devmanzur @jasonhutton-sd Any updates? I got this error too and a little confused

**Comment by kontinuity** [comment]
Solution is here:

https://github.com/Leonidas-from-XIV/node-xml2js/issues/88#issuecomment-1836659197

**Comment by pdowling-udrew** [comment]
If it helps, this error appeared after I upgraded my project from vite 3.2.7 to vite 5.0.2. 

`npm i events` as per @kontinuity 's link solved it.

**Comment by jackytank** [comment]
> If it helps, this error appeared after I upgraded my project from vite 3.2.7 to vite 5.0.2.
> 
> `npm i events` as per @kontinuity 's link solved it.

thats worked for me, tks
