### ISSUE TITLE
return parsed object instead of string ?

### ISSUE THREAD

**Issue by vulkanosaure** [Leonidas-from-XIV/node-xml2js#701]
Hi,

Thanks for the library, it works great.

I was just wondering if there's any way to receive an object (non stringified) rather than a string, i didn't find anything in the doc.
Of course i can call parse, but i think it's a waste because i imagine you must have it as an object and then call stringify on it ? (unless i'm wrong on that point and you directly construct it as a string, in which nvm)

**Comment by Leonidas-from-XIV** [comment]
I don't understand your question because it always returns an object and never stringifies it.

**Comment by vulkanosaure** [comment]
I'm so confused, i just realized i'm using xml-js, I don't know which misclick lead me to your repository instead !
You can ignore/close my question !
(i'll try your lib if i'm not happy with the other one)

**Comment by Leonidas-from-XIV** [comment]
Ah ok, that clears things up!
