### ISSUE TITLE
Convert js2xml (bidirectional conversion)

### ISSUE THREAD

**Issue by DTrejo** [Leonidas-from-XIV/node-xml2js#8]
It would be great if there were bidirectional conversion.

I started working on this, but if there's already something that works for the particular format that xml2js uses, then I'd go with that.

Cheers,
David

**Comment by giuseppe-santoro** [comment]
How can I write out XML after parsing and editing?

**Comment by Leonidas-from-XIV** [comment]
Using the `Builder` class.

**Comment by giuseppe-santoro** [comment]
Ok thank you.
I just found it in the Readme :)

`var fs = require('fs'),
    xml2js = require('xml2js');

var obj = {name: "Super", Surname: "Man", age: 23};

var builder = new xml2js.Builder();
var xml = builder.buildObject(obj);`
