### ISSUE TITLE
calling removeAllListeners() method which doesn't exit

### ISSUE THREAD

**Issue by joselee** [Leonidas-from-XIV/node-xml2js#88]
Tried running a simple test. Here's my server.js: 

var fs = require('fs');
var xml2js = require('xml2js');

var parser = xml2js.Parser();

fs.readFile(__dirname + '/test.xml', function(err, data) {
    parser.parseString(data, function(err, result){
        console.dir(result);
        console.log("done");
    });
});

Console throws an error: Object #<Object> has no method 'removeAllListeners'

Happens on /node_modules/xml2js/lib/xml2js.js:103
trying to do this.removeAllListeners()

**Comment by hatton** [comment]
Note to others that may happen upon this issue, as I did. I had the same error with a _modern_ xml2js (so it wasn't the same problem). The problem was building in an environment (vite with vite-plugin-electron-renderer) that was choking on the cjs nature of this older library. The fix was to tell that environment leave xml2js as an "external package".

**Comment by VaneeOfficialNet** [comment]
Hi @hatton, How do we let Vite know xml2js as external package. I'm facing error:
TypeError: this.removeAllListeners is not a function
    at Parser.reset (parser.js:111:12)

**Comment by hatton** [comment]
See https://vitejs.dev/config/dep-optimization-options.html.  In my case, I have
```
      optimizeDeps: {
        include: ["xml2js", "glob", "fs-extra", "graceful-fs"]
      }
```

**Comment by VaneeOfficialNet** [comment]
Thanks, @hatton ..

**Comment by psantos9** [comment]
Getting the same issue, after adding "optimizeDeps" as recommended by @hatton.
Any other clues here?
Thanks

![Screenshot 2023-05-16 at 18 22 09](https://github.com/Leonidas-from-XIV/node-xml2js/assets/1428629/f4ebdf9f-a95c-4faa-a9a1-3dabfb59225e)

**Comment by Pic212** [comment]
**in my case, installing events solved the issue: npm i events**

Good afternoon, same error, seeking for help please !

Thank you in advance !

Empty NUXT 3 project, npm i xml2js + timers

package.json:
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^18.17.3",
    "nuxt": "^3.6.5"
  },
  "dependencies": {
    "timers": "^0.1.1",
    "xml2js": "^0.6.2"
  }
}

nuxt.config.ts:
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  vite:{
    optimizeDeps: {
      include: ["xml2js"]
    }
  }
})

app.vue:
<template>
  <div>
    <h1>Test XML2JS</h1>
  </div>
</template>

<script setup>
import { parseString } from 'xml2js';
</script>


sax.js:222 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at node_modules/sax/lib/sax.js (sax.js:1565:1)
    at __require (chunk-RSJERJUL.js?v=b6cf498b:3:50)
    at Object.<anonymous> (parser.js:9:9)
    at node_modules/xml2js/lib/parser.js (parser.js:395:4)
    at __require (chunk-RSJERJUL.js?v=b6cf498b:3:50)
    at Object.<anonymous> (xml2js.js:12:12)
    at node_modules/xml2js/lib/xml2js.js (xml2js.js:39:4)
    at __require (chunk-RSJERJUL.js?v=b6cf498b:3:50)
    at xml2js.js:39:13

**Comment by eimlfang** [comment]
@Pic212 is helpful
 ```<script setup> import { parseString } from 'xml2js'; </script> ```

**Comment by jhfoo** [comment]
+1 on @Pic212 's latest answer above:

`npm i events` resolved the error.

**Comment by josephosan** [comment]
same as @jhfoo 
``` npm i events ```. 
and then rerun your project. worked for me.

**Comment by willymateo** [comment]
thanks @josephosan @jhfoo @Pic212 . Installing events resolved the error:
`npm i events`

**Comment by jackytank** [comment]
> thanks @josephosan @jhfoo @Pic212 . Installing events resolved the error: `npm i events`

that work for me, thank you
